PennLINC/xcp_d

docs/.readthedocs.yml
setup.cfg

include 3.7 python

---

xcp_abcd/utils/ciftiseparatemetric.py
xcp_abcd/utils/fcon.py
xcp_abcd/workflow/restingstate.py

fix cifti rules

---

xcp_abcd/utils/modified_data.py

return non masked volume

---

xcp_abcd/interfaces/__init__.py
xcp_abcd/interfaces/regression.py
xcp_abcd/workflow/bold.py
xcp_abcd/workflow/cifti.py

cifti and bold

---

Dockerfile
xcp_abcd/interfaces/filtering.py
xcp_abcd/workflow/base.py
xcp_abcd/workflow/bold.py
xcp_abcd/workflow/cifti.py
xcp_abcd/workflow/postprocessing.py

update workflow docs inside the code

---

.circleci/config.yml
Dockerfile

circleci setup

---

xcp_abcd/cli/run.py
xcp_abcd/workflow/base.py

Test xcp: process both cifti and nifti

---

xcp_abcd/workflow/outputs.py

change clean to residual

---

MANIFEST.in
Makefile
get_version.py

add version automatically

---

xcp_abcd/utils/write_save.py
xcp_abcd/workflow/bold.py

update 3D despike

---

xcp_abcd/interfaces/connectivity.py

one last fix

---

xcp_abcd/interfaces/connectivity.py
xcp_abcd/workflow/bold.py
xcp_abcd/workflow/cifti.py
xcp_abcd/workflow/connectivity.py
xcp_abcd/workflow/outputs.py

200X17 instead of 7

---

.circleci/config.yml
setup.cfg
xcp_abcd/interfaces/__init__.py
xcp_abcd/interfaces/regression.py
xcp_abcd/interfaces/resting_state.py
xcp_abcd/workflow/base.py
xcp_abcd/workflow/bold.py
xcp_abcd/workflow/connectivity.py
xcp_abcd/workflow/restingstate.py

remove brainsprite

---

xcp_abcd/workflow/bold.py
xcp_abcd/workflow/cifti.py
xcp_abcd/workflow/postprocessing.py

adjust RAM for cifti

---

xcp_abcd/cli/run.py
xcp_abcd/cli/run_2.py
xcp_abcd/interfaces/report_core.py
xcp_abcd/workflow/base.py

Cli rewire

---

get_version.py

get automatic version

---

xcp_abcd/utils/utils.py
xcp_abcd/workflow/bold.py
xcp_abcd/workflow/cifti.py
xcp_abcd/workflow/connectivity.py
xcp_abcd/workflow/restingstate.py

update the boilerplate report

---

setup.cfg
xcp_abcd/utils/utils.py

make mni9 as d

---

xcp_abcd/utils/cifitiresample.py
xcp_abcd/workflow/postprocessing.py

Executivesummary

---

Dockerfile

add freesurfer to dockerfile

---

xcp_abcd/utils/__init__.py
xcp_abcd/utils/execsummary.py
xcp_abcd/workflow/base.py

check in some part of summary

---

xcp_abcd/utils/bids.py
xcp_abcd/utils/execsummary.py

add brainsprite utils

---

xcp_abcd/interfaces/connectivity.py
xcp_abcd/interfaces/executesummary.py
xcp_abcd/utils/__init__.py
xcp_abcd/utils/execsummary.py
xcp_abcd/utils/plot.py

executive summary joints parts

---

docs/.readthedocs.yml
docs/index.rst

get update from main

---

.vscode/settings.json
xcp_abcd/interfaces/__init__.py
xcp_abcd/interfaces/surfplotting.py
xcp_abcd/utils/__init__.py
xcp_abcd/utils/plot.py
xcp_abcd/utils/utils.py
xcp_abcd/workflow/__init__.py
xcp_abcd/workflow/anatomical.py
xcp_abcd/workflow/base.py
xcp_abcd/workflow/bold.py
xcp_abcd/workflow/cifti.py
xcp_abcd/workflow/execsummary.py

preventing `circular import` python 3.8 and above

---

xcp_abcd/interfaces/surfplotting.py
xcp_abcd/utils/bids.py
xcp_abcd/workflow/anatomical.py
xcp_abcd/workflow/execsummary.py

Executivesummaryp1

---

.circleci/config.yml
setup.cfg
xcp_abcd/interfaces/report.py
xcp_abcd/interfaces/report_core.py
xcp_abcd/interfaces/surfplotting.py
xcp_abcd/utils/__init__.py
xcp_abcd/utils/bids.py
xcp_abcd/utils/execsummary.py
xcp_abcd/utils/plot.py
xcp_abcd/utils/utils.py
xcp_abcd/workflow/anatomical.py
xcp_abcd/workflow/base.py
xcp_abcd/workflow/bold.py
xcp_abcd/workflow/cifti.py
xcp_abcd/workflow/execsummary.py

update from exec summ

---

.circleci/config.yml
Dockerfile
xcp_abcd/data/license.txt

Executivesummarypt2

---

.circleci/config.yml

docker tag

---

versioneer.py
xcp_abcd/cli/run.py
xcp_abcd/interfaces/__init__.py
xcp_abcd/interfaces/constants.py
xcp_abcd/interfaces/helpers.py
xcp_abcd/interfaces/layout_builder.py
xcp_abcd/interfaces/report_core.py
xcp_abcd/utils/execsummary.py
xcp_abcd/workflow/anatomical.py
xcp_abcd/workflow/base.py
xcp_abcd/workflow/execsummary.py

Executive summary framework completed

---

setup.cfg

change sphinx version for docs

---

docs/conf.py

change Theme

---

setup.cfg

[skip ci] add  sphinx 

---

docs/environment.yml
docs/requirements.txt
setup.cfg

[skip ci] sphinx 

---

docs/conf.py
docs/requirements.txt

[skip ci] add sphinx to docs

---

docs/requirements.txt
setup.cfg

add python 3.7 temporarily for building docs

---

docs/docker.rst
docs/index.rst
docs/singularity.rst

add docker and singularity

---

xcp_abcd/workflow/connectivity.py

remove labelled

---

xcp_abcd/workflow/bold.py

increased bold memgb size

---

xcp_abcd/interfaces/prepostcleaning.py
xcp_abcd/workflow/postprocessing.py

correct dummy for cifti 

---

.circleci/config.yml
README.rst
docs/docker.rst
docs/generalworkflow.rst
docs/installation.rst
docs/singularity.rst
docs/usage.rst
xcp_abcd/cli/run.py
xcp_abcd/interfaces/report_core.py
xcp_abcd/utils/confounds.py
xcp_abcd/utils/dcan2fmriprep.py
xcp_abcd/workflow/anatomical.py
xcp_abcd/workflow/base.py

the read me on the page of the github

update read me #198

---

xcp_abcd/interfaces/prepostcleaning.py
xcp_abcd/utils/modified_data.py

change interpolation method

---

xcp_abcd/interfaces/filtering.py
xcp_abcd/utils/modified_data.py

interpolate

---

xcp_abcd/utils/modified_data.py

remove printing node/voxel

---

xcp_abcd/utils/concantenation.py

adjust str out

---

xcp_abcd/utils/concantenation.py
xcp_abcd/utils/utils.py

add aroma docs

---

xcp_abcd/utils/confounds.py
xcp_abcd/utils/plot.py

finally aroma

---

xcp_abcd/interfaces/constants.py
xcp_abcd/interfaces/surfplotting.py
xcp_abcd/utils/plot.py

increase thickness of plot 

---

xcp_abcd/utils/modified_data.py

NAN during interpolation, set hi frequency to nyquist instead of 1 

---

xcp_abcd/interfaces/report_core.py
xcp_abcd/utils/concantenation.py

separate cifti and nifti concatenation

---

xcp_abcd/utils/concantenation.py

avoid concatenation when `run-x` is less than 1

[FIX] `run-x` must be more than 1 for concatenation 

---

Dockerfile

concatenation  done completely 

---

xcp_d/interfaces/prepostcleaning.py
xcp_d/utils/execsummary.py
xcp_d/utils/plot.py

Azeez branch

---

.circleci/tests/test_example.py
xcp_d/workflow/anatomical.py
xcp_d/workflow/base.py
xcp_d/workflow/bold.py
xcp_d/workflow/cifti.py
xcp_d/workflow/connectivity.py
xcp_d/workflow/execsummary.py
xcp_d/workflow/outputs.py
xcp_d/workflow/postprocessing.py
xcp_d/workflow/restingstate.py

reflow code in workflows to be pep8 compliant

[RF] pep8 style for the workflows

---

.circleci/tests/test_FD.py
xcp_d/cli/run.py
xcp_d/interfaces/prepostcleaning.py
xcp_d/interfaces/qc_plot.py
xcp_d/interfaces/regression.py
xcp_d/utils/confounds.py
xcp_d/workflow/base.py
xcp_d/workflow/bold.py
xcp_d/workflow/cifti.py
xcp_d/workflow/postprocessing.py

Refactoring confounds.py in Utils

 [RF] Confounds.py in Utils

---

.circleci/config.yml
Dockerfile
xcp_d/data/nipreps.json
xcp_d/interfaces/ants.py
xcp_d/interfaces/c3.py
xcp_d/interfaces/workbench.py
xcp_d/utils/bids.py
xcp_d/workflow/anatomical.py

[ENH] Anatomical/Surface workflows

---

.circleci/tests/test_despike.py
xcp_d/interfaces/prepostcleaning.py
xcp_d/interfaces/qc_plot.py
xcp_d/interfaces/regression.py
xcp_d/utils/plot.py
xcp_d/utils/write_save.py
xcp_d/workflow/bold.py

added comments explaining despiking and renamed variables in despike

---

xcp_d/utils/filemanip.py

adds the rest of the CIFTI-2 extensions to special_extensions
- filemanip.py: add the rest of the multi-part CIFTI-2 extensions to the list "special_extensions" so that filemanip functions treat them like single-part extensions.

ENH: Update filemanip.py "special_extensions" with the rest of the CIFTI-2 multi-part extensions

---

.circleci/tests/test_interpolation.py
xcp_d/interfaces/prepostcleaning.py
xcp_d/interfaces/regression.py
xcp_d/utils/__init__.py
xcp_d/utils/modified_data.py

Testing and refactoring interpolation workflow

[RF] Interpolation

---

xcp_d/workflow/anatomical.py

Remove enhancet1w node for M1 compatibility

Fix malloc failure

---

xcp_d/workflow/bold.py
xcp_d/workflow/restingstate.py

Smoothing workflow refactor and testing

[RF] Smoothing

---

xcp_d/utils/utils.py
xcp_d/workflow/base.py

Elegant error messages, typos, readability, etc.

[RF] Miscellaneous

---

.circleci/tests/test_ALFF.py
.circleci/tests/test_ReHo.py
xcp_d/interfaces/resting_state.py
xcp_d/utils/fcon.py
xcp_d/utils/write_save.py
xcp_d/workflow/restingstate.py

Test and refactor ReHo computation workflow

[RF] Reho Computation

---

docs/docker.rst
docs/generalworkflow.rst
docs/output.rst
docs/usage.rst
xcp_d/cli/run.py
xcp_d/workflow/outputs.py

Updates to the read-the-docs based on RF, misc. typos

[DOC] Update docs

---

xcp_d/utils/utils.py

[RF] fixes

---

.circleci/tests/test_ALFF.py
.circleci/tests/test_ReHo.py
xcp_d/interfaces/qc_plot.py
xcp_d/interfaces/surfplotting.py
xcp_d/utils/__init__.py
xcp_d/utils/bids.py
xcp_d/utils/concantenation.py
xcp_d/utils/execsummary.py
xcp_d/utils/plot.py
xcp_d/utils/utils.py
xcp_d/workflow/bold.py
xcp_d/workflow/cifti.py
xcp_d/workflow/execsummary.py

Refactor/ test executive summary

[RF] Executive summary

---

xcp_d/interfaces/qc_plot.py
xcp_d/interfaces/report.py
xcp_d/utils/concantenation.py
xcp_d/utils/plot.py
xcp_d/workflow/outputs.py

[RF] Compute qcplot.py

---

LICENSE
docs/index.rst
docs/license.rst

Closes None.
- Replace the MIT license in `LICENSE` with the BSD-3 license mentioned in `setup.cfg` and the pull request template.
- Remove the empty `docs/license.rst` file and link to the updated `LICENSE` file in `docs/index.rst`.
- The main documentation page, since the license is now included.

[FIX] Replace MIT license with BSD-3

---

xcp_d/utils/utils.py

Fixing MNI import for Lin6 (typo in "Asym")

Update utils.py to fix MNILin6 imports

---

README.rst

Add RTD, CircleCI, Docker, GitHub, and license badges to the README.
Just the badges. Are there any others we want?

[DOC] Add badges to README

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
docs/usage.rst

Create bug report and feature request issue templates.
Add a link to NeuroStars on the issue-opening page for usage questions.
Add a link to `docs/usage.rst` too.
The templates should be reviewed, along with `docs/usage.rst`.

[DOC] Add issue templates and route to NeuroStars

---

.circleci/get_data.sh
.circleci/tests/test_interpolation.py
.circleci/tests/test_utils_write_save.py
xcp_d/utils/plot.py
xcp_d/utils/write_save.py

Closes #448.
One question- does scaling need to be a part of the read/write process? It seems like it should be separated out.
To do:
- Use `nilearn.masking.apply_mask` to nifti images, instead of directly masking the data numpy array with the mask numpy array. Nilearn's pretty good at flagging incompatible headers, so it should catch any issues that the old version might have missed.
- Simplify (hopefully) the cifti image loading and saving processes. I don't think we need temporary files.
- Sort imports in `xcp_d.utils.write_save`.
None, AFAIK.

[REF] Use nilearn for loading and masking nifti data

---

.github/workflows/lint.yml
pyproject.toml
setup.cfg

Related to, but does not close, #471.
- Create a GitHub workflow that lints the `xcp_d` code.
- Use flake8, flake8-absolute-import, flake8-docstrings, flake8-isort, flake8-unused-arguments, flake8-use-fstring, flake8-warnings, and pep8-naming for the check.
None.

[TST] Add linting GH workflow

---

xcp_d/__about__.py
xcp_d/__main__.py
xcp_d/cli/run.py
xcp_d/cli/version.py
xcp_d/interfaces/__init__.py
xcp_d/interfaces/c3.py
xcp_d/interfaces/connectivity.py
xcp_d/interfaces/filtering.py
xcp_d/interfaces/layout_builder.py
xcp_d/interfaces/prepostcleaning.py
xcp_d/interfaces/qc_plot.py
xcp_d/interfaces/regression.py
xcp_d/interfaces/report_core.py
xcp_d/interfaces/resting_state.py
xcp_d/interfaces/surfplotting.py
xcp_d/interfaces/workbench.py
xcp_d/utils/__init__.py
xcp_d/utils/concantenation.py
xcp_d/utils/plot.py
xcp_d/utils/sentry.py
xcp_d/workflow/__init__.py
xcp_d/workflow/anatomical.py
xcp_d/workflow/base.py
xcp_d/workflow/bold.py
xcp_d/workflow/cifti.py
xcp_d/workflow/connectivity.py
xcp_d/workflow/execsummary.py
xcp_d/workflow/outputs.py
xcp_d/workflow/postprocessing.py
xcp_d/workflow/restingstate.py

Related to, but does not close, #471.
Replace all relative paths in the codebase with absolute ones.
Rename the class `layout_builder` to `LayoutBuilder`.
None.

[REF] Replace all relative imports with absolute ones

---

.github/config.yml
.github/pull_request_template.md

Closes None.
Replace the extra "new contributors" text in the pull request template with a welcome bot App.
None.

[DOC] Use welcome bot to comment on new contributors' PRs

---

.circleci/tests/conftest.py
.circleci/tests/test_FCON.py
.circleci/tests/test_FD.py
.circleci/tests/test_Reg.py
.circleci/tests/test_TR.py
.circleci/tests/test_despike.py
.circleci/tests/test_filtering.py
.circleci/tests/test_interpolation.py
.circleci/tests/test_smoothing.py
.circleci/tests/test_utils_write_save.py
setup.cfg
xcp_d/interfaces/__init__.py
xcp_d/interfaces/ants.py
xcp_d/interfaces/c3.py
xcp_d/interfaces/connectivity.py
xcp_d/interfaces/filtering.py
xcp_d/interfaces/layout_builder.py
xcp_d/interfaces/prepostcleaning.py
xcp_d/interfaces/qc_plot.py
xcp_d/interfaces/regression.py
xcp_d/interfaces/report.py
xcp_d/interfaces/report_core.py
xcp_d/interfaces/resting_state.py
xcp_d/interfaces/surfplotting.py
xcp_d/interfaces/workbench.py

Related to, but does not close, #471.
- Sort imports in interfaces files.
- Make utils imports in interfaces more specific.
- Address docstring issues in interfaces.
- PEPify CircleCI tests.
None.

[REF] Lint interfaces

---

xcp_d/workflow/__init__.py
xcp_d/workflow/anatomical.py
xcp_d/workflow/base.py
xcp_d/workflow/bold.py
xcp_d/workflow/cifti.py
xcp_d/workflow/connectivity.py
xcp_d/workflow/execsummary.py
xcp_d/workflow/outputs.py
xcp_d/workflow/postprocessing.py
xcp_d/workflow/restingstate.py

Related to, but does not close, https://github.com/PennLINC/xcp_d/issues/471.
- Sort imports in interfaces files.
- Make utils imports in interfaces more specific.
- Address docstring issues in interfaces.
- PEPify CircleCI tests.
None.

[REF] Lint workflows

---

xcp_d/cli/run.py
xcp_d/interfaces/constants.py
xcp_d/interfaces/layout_builder.py
xcp_d/utils/plot.py
xcp_d/utils/sentry.py
xcp_d/workflow/base.py
xcp_d/workflow/bold.py
xcp_d/workflow/cifti.py
xcp_d/workflow/connectivity.py
xcp_d/workflow/outputs.py
xcp_d/workflow/postprocessing.py
xcp_d/workflow/restingstate.py

- Remove variables that are not being used

[RF] Get rid of unused variables

---

.gitignore
docs/api.rst
docs/conf.py
docs/index.rst
docs/workflows.rst
setup.cfg

Closes None.
- Do a bunch of stuff with the conf.py file. Need to actually catalogue the changes.
- Build the API documentation.
- I'm still looking at ~80 warnings about the docstring formatting when I build the docs locally, but I don't want to tackle all of that in this PR.
The API docs, mainly.

[DOC] Add API to documentation

---

.circleci/CiftiWithFreeSurferTest.sh
.circleci/config.yml

Closes None, but addresses something discussed offline.
- Store the artifacts (just derivatives) for each of the CircleCI tests.

[TST] Store CircleCI artifacts

---

.github/release.yml
docs/dev_guide.rst

- Create a release notes template config file.

Add release notes template

---

docs/usage.rst

Add warning to documentation about M1 chip

---

.circleci/RunPyTests.sh
docs/dev_guide.rst

Closes None.
- Fix the local command in `RunPyTests.sh`.
- Include the tests folder in the test setup instructions within the developer's guide.

Fix the local pytest script and documentation

---

xcp_d/interfaces/regression.py
xcp_d/utils/confounds.py

update datafile --> original_file in load_aroma

[FIX] Update load_aroma so the correct file is being read in

---

CITATION.cff

This is a little late, but I forgot to bump the xcpd version in the CFF file before releasing 0.2.0 🤦. Also, I have added myself to the file. We might want to reorder the authors when it comes time to write the software paper, but I added myself after Kahini since I'm a major contributor (like Azeez, Kahini, and Max), but joined later.

Update CITATION.cff file for 0.2.0

---

xcp_d/utils/bids.py

Adds back in the resolution/density filters to `collect_data`, removed in #602.

Revert removed code from nibabies PR

---

.circleci/config.yml
CITATION.cff

Fixes a bug in 0.2.2 and 0.3.0.

Run the full CircleCI workflow on releases

---

.circleci/Nibabies.sh
docs/generalworkflow.rst
xcp_d/cli/run.py
xcp_d/utils/utils.py

Closes #514.
- Remove `--nuissance-regressors`.
- Remove `--bandpass_filter <true|false>`

Remove `--nuissance-regressors` and `--bandpass_filter`

---

setup.cfg

So that HCP ingression will run

Add masks to package data

---

xcp_d/utils/bids.py
xcp_d/workflow/anatomical.py
xcp_d/workflow/execsummary.py

Closes #707.
- Create function to get the freesurfer folder: `utils.bids.get_freesurfer_dir`.
- Use the new function in the anatomical workflow and the executive summary.

Improve identification of FreeSurfer derivatives

---

.circleci/tests/test_confounds.py

Closes #598 and closes #678.
- Add test for confounds-loading function.
- Add test for confounds-describing function.
None

Add tests for confound loading function

---

xcp_d/utils/bids.py
xcp_d/workflow/base.py

Closes None. This breaks out a piece of #706 (which has a breaking change) to merge for #702 and #721.
- Create a new function, `collect_surface_data`, to collect the surface files needed for the anatomical and brainsprite workflows.
None

Collect preprocessed surfaces in new function

---

CITATION.cff
xcp_d/cli/run.py

Closes None.
- Update the CITATION.cff file for the 0.3.1 release.
- Remove the outdated _DeprecatedStoreAction030.
None.

Prepare for 0.3.1 release

---

CITATION.cff

Closes None.
- Update the CITATION.cff file for the 0.3.2 release.
None.

Prepare for 0.3.2 release

---

.circleci/config.yml

Closes #585.
- Add orb and upload steps to push coverage report to CodeCov.

Upload coverage reports to CodeCov

---

README.rst

Add CodeCov badge to README

---

docs/api.rst
xcp_d/workflow/anatomical.py

Closes None.
- Fix typos in API lines.
- Fix typo in workflow graph call.

Fix typos in documentation

---

docs/usage.rst

Closes #557.
- List the allowed output spaces for preprocessed data in the usage documentation.
usage.rst

Add information about preprocessing requirements

---

xcp_d/interfaces/filtering.py
xcp_d/interfaces/regression.py
xcp_d/interfaces/resting_state.py
xcp_d/interfaces/surfplotting.py
xcp_d/tests/test_confounds.py
xcp_d/tests/test_reho.py
xcp_d/tests/test_smoothing.py
xcp_d/tests/utils.py
xcp_d/utils/dcan2fmriprep.py
xcp_d/utils/fcon.py

Closes None.
- Run black on the codebase, using the newest version.

Autoformat code with new version of black

---

Dockerfile
setup.cfg

Copy of #794 for 0.3.x series. See #794 for details.

0.3.x: Change permissions of miniconda folders in Dockerfile

---

.circleci/config.yml
Dockerfile

Use rc6 build image

---

.circleci/config.yml
Dockerfile
README.rst
setup.cfg

Closes None.
- Remove the now archived codecov dependency.

Remove codecov dependency

---

xcp_d/data/executive_summary_templates/executive_summary.html.jinja
xcp_d/interfaces/execsummary.py

Closes #853.
- Add boilerplate generated by the main workflow to the bottom of the executive summary.

Add boilerplate to the executive summary

---

README.rst

Update docs to mention HCPYA version

---

README.rst

Closes #500.
- Say what XCP-D is good for and what it's not good for.
- The main RTD file.

Describe scope of XCP-D

---

CODE_OF_CONDUCT.md
docs/contributing.rst

Closes #892.
- Add code of conduct based on contributor's covenant.
- Add style guide to contributing guidelines.

Add contributing documentation

---

xcp_d/data/boilerplate.bib
xcp_d/interfaces/plotting.py
xcp_d/utils/qcmetrics.py
xcp_d/workflows/plotting.py

Closes None, but continues work on #891.
- Add metadata about the coregistration and normalization QC metrics.

Improve QC sidecar contents

---

xcp_d/tests/test_utils_doc.py
xcp_d/tests/test_utils_utils.py

References #895.
- Add tests for functions in xcp_d.utils.utils.

Add tests for xcp_d.utils.utils module

---

xcp_d/tests/test_utils_execsummary.py
xcp_d/tests/test_utils_utils.py
xcp_d/utils/utils.py

References #895.
- Add tests for functions in xcp_d.utils.execsummary.

Add tests for xcp_d.utils.execsummary module

---

xcp_d/interfaces/plotting.py
xcp_d/tests/test_utils_plotting.py
xcp_d/workflows/base.py
xcp_d/workflows/bold.py
xcp_d/workflows/cifti.py
xcp_d/workflows/concatenation.py
xcp_d/workflows/plotting.py

Closes #914.
- Standardize executive summary carpet if params is "none".

Standardize executive summary carpet if params is "none"

---

xcp_d/cli/run.py
xcp_d/tests/test_cli_run.py

References #895.
- Move parts of `build_workflow` that validate parameters into new function, `_validate_parameters`.
- Add tests to cover `_validate_parameters`.

Test CLI parameter validation

---

xcp_d/tests/test_utils_bids.py
xcp_d/utils/bids.py
xcp_d/workflows/base.py

Closes #906.
- Split up `collect_surface_data` into `collect_mesh_data` and `collect_morphometry_data`.

Refactor collection functions

---

xcp_d/cli/run.py
xcp_d/tests/test_cli.py
xcp_d/tests/test_cli_run.py

Closes #929.
- Add the new parameter to the CLI.
- Test the new parameter.

Add `--fs-license-file` parameter to command line interface

---

CITATION.cff
docs/changes.md

Why can't I ever remember to do this _before_ making the release???
- Update version and release date in CITATION.cff.
- Add release notes for 0.5.0 to changelog.

Update documentation for 0.5.0 release

---

CITATION.cff
docs/changes.md

Closes none.
- Update the changelog file with 0.5.1 release notes.
- Update the CITATION.cff.

Update docs for 0.5.1

---

xcp_d/utils/hcp2fmriprep.py

Fix HCP ingression for non-rest tasks.

---

xcp_d/workflows/execsummary.py

Closes #663.
- Allow the registration figure grabbed by the executive summary to have "desc-flirtbbr".

Look for flirtbbr figure

---

.readthedocs.yaml
xcp_d/workflows/execsummary.py

Closes none, but apparently #980 didn't fix #663.
- Allow the registration figure to be missing.
- Install graphviz (for workflow plots) for RTD.

Make registration figure in executive summary optional

---

xcp_d/utils/hcp2fmriprep.py

Fix HCP ingression for non-rest tasks

---

xcp_d/workflows/execsummary.py

References #663.
- This should work when there are multiple sessions.
- Allow `flirtnobbr` for the file's description.

Allow executive summary registration figure to really be empty

---

xcp_d/interfaces/connectivity.py
xcp_d/tests/test_workflows_connectivity.py
xcp_d/workflows/connectivity.py

Closes #978.
- Add communities to the connectivity plots.

Improve connectivity plots

---

CITATION.cff
docs/changes.md

Closes none.
- Update CITATION.cff with new version number.
- Update changelog with new release notes.

Prepare for 0.6.0

---

.github/dependabot.yml

Closes none. Related to https://github.com/PennLINC/aslprep/pull/365.
- Add dependabot config file.

Add dependabot Action

---

.github/dependabot.yml

Closes none, but relates to #1006.

Use Dependabot to check Python dependencies

---

.circleci/config.yml
.github/workflows/lint.yml
.readthedocs.yaml
Dockerfile
docs/contributing.rst
docs/installation.rst
pyproject.toml
xcp_d/interfaces/plotting.py
xcp_d/tests/conftest.py
xcp_d/tests/run_local_tests.py
xcp_d/tests/test_utils_bids.py
xcp_d/tests/test_utils_utils.py

Closes none.
- Update Python installation to Python 3.10.

Update to Python 3.10

---

xcp_d/tests/test_cli.py
xcp_d/tests/utils.py
xcp_d/utils/bids.py

Closes #1057.
- Reproduce #1057.
- Look for either T1w _or_ T2w transforms in `collect_data`.

Address bug with T2w-only processing

---

xcp_d/utils/bids.py

Closes #1062.
- Use a combination of `strict=True` and `ignore_strict_entities` options in `BIDSLayout.get_nearest` for run data collection.

Use strict file-matching in collect_run_data

---

docs/changes.md

Add release notes for releases 0.6.1 and 0.6.2

---

CITATION.cff
docs/changes.md

Closes none.
- Update the changelog with 0.6.3 release notes.
- Update the CITATION.cff file's version (forgot to do this for the last few releases)

Update changelog for 0.6.3

---

docs/workflows.rst

Added information from the manuscript

Add information about ReHo to read-the-docs

---

README.rst

The recent commit changed file name.
None

Fix image link

---

CITATION.cff
docs/changes.md

Closes none
- Update changelog.
- Update CITATION.cff.

Prepare for 0.7.0 release

---

xcp_d/cli/parser.py
xcp_d/config.py
xcp_d/tests/test_cli.py

Closes #1110.
- Change default `--min-time` from 100 to 240.

Change default `--min-time` from 100 to 240

---

xcp_d/cli/parser.py
xcp_d/config.py
xcp_d/tests/tests.py

Closes #954.
- Add `--bids-database-dir` parameter.
- Propagate the `bids_database_dir` Config value where fMRIPrep uses it.

Add `--bids-database-dir` parameter

---

pyproject.toml

Closes none.
- Pin a number of dependency versions to fix the RTD build. I'll leave it to dependabot to help me pin down the source of the issue.

Pin dependencies to fix RTD build

---

xcp_d/interfaces/nilearn.py
xcp_d/tests/test_utils_utils.py
xcp_d/utils/utils.py

Closes none.
- Use simulated data to test the denoising function.

Improve denoising tests

---

CITATION.cff
docs/changes.md

Closes none.
- Update the changelog and CITATION.cff for 0.7.1.

Prepare for 0.7.1 release

---

CITATION.cff
docs/changes.md

Prepare for 0.7.4 release

---

CITATION.cff
docs/changes.md

Prepare for 0.7.5 release

---

xcp_d/workflows/anatomical.py

Closes none.
- Improve the docstring of `init_postprocess_surfaces_wf`.
- Replace `fmt:off` with `fmt:skip` in anatomical workflow connections.

Document anatomical workflow in more detail

---

docs/outputs.rst
docs/usage.rst
xcp_d/cli/parser.py
xcp_d/utils/boilerplate.py

Closes none.
- Add important documentation regarding the MIDB and Myers-Labonte atlases added in #1192.
- Fix CLI help message formatting. Bug was introduced in #1109.

Fix up documentation

---

docs/outputs.rst

Closes none. Thanks for catching this @erikglee!

Add references section to outputs page

---

xcp_d/interfaces/bids.py
xcp_d/interfaces/workbench.py
xcp_d/workflows/anatomical.py

Closes none.
- Improve docstrings and comments in anatomical workflow.

Continue to improve documentation of anatomical workflow

---

CITATION.cff
docs/changes.md

Prepare for 0.8.0 release

---

.github/ISSUE_TEMPLATE/mode_request.md
docs/contributing.rst
docs/workflows.rst

Document how to request a new mode

---

.circleci/config.yml
Dockerfile

Hopefully helps with #1288.
- Update xcpd_build image from 0.0.19 to 0.0.20 (https://github.com/PennLINC/xcpd_build/pull/40).

Update build image version

---

.circleci/config.yml

This started when I downgraded connectome workbench, so maybe there's a memory issue.

Fix resource class of CIFTI tests

---

xcp_d/workflows/anatomical/surface.py

Closes none.
- Simplify the handling of the brainsprite workflow in `init_postprocess_surfaces_wf`.

Simplify the brainsprite workflow setup

---

xcp_d/workflows/base.py

Do not attempt to concatenate runs when no runs in entity set are processed

---

xcp_d/cli/parser.py

Note that automatic head radius estimation gives higher values than 50

---

CITATION.cff
docs/changes.md

Prepare for 0.10.6

---

docs/conf.py
xcp_d/cli/parser_utils.py
xcp_d/interfaces/execsummary.py
xcp_d/utils/sentry.py
xcp_d/workflows/anatomical/surface.py

Closes #1376.
- Warp surfaces to NLin6 space even if they're provided in fsLR space.

Warp fsLR surfaces to NLin6 for brainsprite

---

xcp_d/tests/test_workflows_anatomical.py
xcp_d/workflows/anatomical/surface.py

Run vertex normalization on output surfaces

---

xcp_d/interfaces/nilearn.py
xcp_d/utils/bids.py
xcp_d/workflows/anatomical/plotting.py
xcp_d/workflows/anatomical/volume.py
xcp_d/workflows/base.py
xcp_d/workflows/bold/cifti.py
xcp_d/workflows/bold/nifti.py
xcp_d/workflows/bold/plotting.py

Closes #1422.
- Apply brain mask to anatomical and functional images before they're used in registration plots in the executive summary.

Use masked functional and anatomical images for executive summary

---

README.rst
xcp_d/ingression/hcpya.py
xcp_d/tests/test_smoothing.py

Update note about HCP compatibility

---

.circleci/config.yml
Dockerfile
pyproject.toml
xcp_d/cli/run.py
xcp_d/interfaces/bids.py
xcp_d/interfaces/nilearn.py
xcp_d/interfaces/plotting.py
xcp_d/tests/test_cli.py
xcp_d/tests/test_smoothing.py
xcp_d/tests/test_utils_utils.py
xcp_d/utils/restingstate.py
xcp_d/utils/utils.py
xcp_d/utils/write_save.py
xcp_d/workflows/anatomical/volume.py
xcp_d/workflows/bold/metrics.py
xcp_d/workflows/bold/plotting.py
xcp_d/workflows/bold/postprocessing.py

Use MNIInfant transforms from templateflow
