PennLINC/xcp_d

xcp_abcd/utils/modified_data.py
Normalise the reconstructed spectrum. 
This is necessary when the oversampling frequency exceeds 1 and minimum of 4 is required
=> Normalise the reconstructed spectrum

xcp_abcd/utils/confounds.py
Changes acompcor loading strategy to be compatible with fMRIPrep 21.0.0+ (#267)
This update makes acompcor component loading compatible with previous and newer versions of fMRIPrep
No documentation should be changed.
=> [Fix] Update confounds.py

pyproject.toml, setup.py
Remove SETUP_REQUIRES from setup.py. pyproject.toml handles it.
None
Here is the full traceback for the failing RTD build:
```
Processing /home/docs/checkouts/readthedocs.org/user_builds/xcp-d/checkouts/475
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'error'
error: subprocess-exited-with-error
× Preparing metadata (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [64 lines of output]
running dist_info
creating /tmp/pip-modern-metadata-7xxvzll7/xcp_d.egg-info
writing …
```
=> [FIX] Address failing RTD build

xcp_d/utils/__init__.py, xcp_d/utils/bids.py, xcp_d/utils/cifticonnectivity.py, xcp_d/utils/ciftiparcellation.py, xcp_d/utils/ciftiresample.py, xcp_d/utils/ciftiseparatemetric.py, xcp_d/utils/concantenation.py, xcp_d/utils/dcan2fmriprep.py, xcp_d/utils/execsummary.py, xcp_d/utils/filemanip.py, xcp_d/utils/hcp2fmriprep.py, xcp_d/utils/modified_data.py, xcp_d/utils/plot.py, xcp_d/utils/qcmetrics.py, xcp_d/utils/restingstate.py, xcp_d/utils/sentry.py, xcp_d/utils/utils.py, xcp_d/utils/write_save.py
Related to, but does not close, https://github.com/PennLINC/xcp_d/issues/471.
- Make utils imports more specific, to prevent circular imports.
- Run isort on `utils.__init__.py`.
- Work on standardizing docstrings in the `utils` module.
None.
=> [REF] Lint utils

.circleci/tests/test_Reg.py, .circleci/tests/test_interpolation.py, setup.cfg, xcp_d/interfaces/__init__.py, xcp_d/interfaces/ants.py, xcp_d/interfaces/c3.py, xcp_d/interfaces/connectivity.py, xcp_d/interfaces/filtering.py, xcp_d/interfaces/prepostcleaning.py, xcp_d/interfaces/qc_plot.py, xcp_d/interfaces/regression.py, xcp_d/interfaces/report.py, xcp_d/interfaces/resting_state.py, xcp_d/interfaces/surfplotting.py, xcp_d/interfaces/workbench.py, xcp_d/notebooks/restingstate.ipynb, xcp_d/utils/__init__.py, xcp_d/utils/cifticonnectivity.py, xcp_d/utils/ciftiparcellation.py, xcp_d/utils/ciftiresample.py, xcp_d/utils/ciftiseparatemetric.py, xcp_d/workflow/anatomical.py, xcp_d/workflow/base.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py, xcp_d/workflow/connectivity.py, xcp_d/workflow/execsummary.py, xcp_d/workflow/outputs.py, xcp_d/workflow/restingstate.py
Related to, but does not close, #471.
- Add leading underscore to all Nipype InputSpecs and OutputSpecs.
- Rename any non-CamelCase class names to CamelCase.
- connectplot --> ConnectPlot
- interpolate --> Interpolate
- computeqcplot --> QCPlot
- ciftidespike --> CiftiDespike
- regress --> Regress
- brainplot --> BrainPlot
- computealff --> ComputeALFF
- surfaceReho --> SurfaceReHo
- Ignore some variable-naming style checks. I'd like to re-enable these in the future, but I think we can skip them for now.
None.
=> [REF] Rename classes to CamelCase

xcp_d/interfaces/bids.py, xcp_d/workflow/anatomical.py, xcp_d/workflow/base.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py, xcp_d/workflow/execsummary.py, xcp_d/workflow/outputs.py
Closes #449. I don't think this is the best solution long-term (e.g., we could just import DerivativesDataSink from `niworkflows` and change the `out_path_base` in `xcp_d`- see #488), but it's a good solution for now.
- Rename the main definition of DerivativesDataSink to BaseDerivativesDataSink.
- Define DerivativesDataSink (inheriting from BaseDerivativesDataSink), with the appropriate `out_path_base`, in `interfaces.bids`.
- Import the new DerivativesDataSink, without modifying it, throughout the rest of the package.
None.
=> [REF] Centralize DerivativesDataSink definition

.circleci/NiftiWithoutFreeSurferTest.sh, xcp_d/cli/run.py, xcp_d/notebooks/hcp2fmriprep.py, xcp_d/utils/confounds.py, xcp_d/utils/plot.py, xcp_d/workflow/base.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py, xcp_d/workflow/outputs.py, xcp_d/workflow/postprocessing.py
- Create a new command-line argument, `--nuisance-regressors`, that is mutually exclusive with the existing `--nuissance-regressors` parameter.
- Raise a warning when users use `--nuissance-regressors`, with a note that the parameter will be removed in 0.1.6 (two releases from next).
None.
=> [FIX] Deprecate nuissance-regressors in favor of nuisance-regressors

.circleci/get_data.sh
- Ensure that the local xcp_d path exists, and raise an error if it doesn't. Previous it would just raise a warning, then continue on using the version in the Docker file.
- Don't call `setopt` unless the shell is zsh, instead of the opposite.
- Make sure a few other things in `get_data.sh` are treated as strings.
None.
=> [TST] Make local tests stricter

xcp_d/interfaces/connectivity.py, xcp_d/interfaces/filtering.py, xcp_d/interfaces/prepostcleaning.py, xcp_d/interfaces/qc_plot.py, xcp_d/interfaces/regression.py, xcp_d/interfaces/resting_state.py, xcp_d/interfaces/surfplotting.py
- In several files, the field "manadatory" is used instead of "mandatory". This replaces all uses of the former with the latter.
None.
=> [FIX] Fix "manadatory" typo in interfaces

xcp_d/cli/run.py
Closes #554. AFAICT, running `xcp_d` with `--input-type hcp` would currently raise an error, but `--input-type hpc` wouldn't reach any of the necessary code, because `hcp` is used in all of the rest of the codebase, so I'm not counting this PR as a breaking change.
- Change "hpc" (a typo) in the command-line interface to "hcp" (Human Connectome Project).
None.
=> [FIX] Change "hpc" in CLI to "hcp"

setup.cfg
Follow-up to #320-- changes pybids req from >= 0.14.0 to ~=0.15.1. 
pybids 0.15.0 and up retain zero-padding of BIDS run indices (when the indices are read in as int type), whereas in < 0.15.0 zero-padding is removed. This fixes an error where filenames of residual BOLD files and their corresponding figures would be mismatched (due to removal of zero-padding in the BOLD files, but not the figures since the figures are never read in with pybids)
=> [ENH/FIX] Update required pybids ver

.circleci/cifti_with_freesurfer_outputs.txt, .circleci/nifti_with_freesurfer_outputs.txt, .circleci/nifti_without_freesurfer_outputs.txt, docs/output.rst, xcp_d/interfaces/prepostcleaning.py, xcp_d/interfaces/qc_plot.py, xcp_d/interfaces/surfplotting.py, xcp_d/utils/plot.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py, xcp_d/workflow/execsummary.py, xcp_d/workflow/outputs.py
Closes None. I realized that, since we now output the filtered framewise displacement time series in a TSV with a header, there's no reason we shouldn't output the other filtered motion parameters as well.
- Include the other filtered motion parameters in the `motion.tsv` output.
- Rename `desc-framewisedisplacement_motion.tsv` to `desc-filtered_motion.tsv` or `motion.tsv`, depending on if filtering was done or not.
=> Output all filtered motion parameters

.circleci/tests/test_Reg.py, xcp_d/interfaces/regression.py, xcp_d/utils/confounds.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py
We noticed a substantial bug in which the requested parameters were not being used in the regression step. Instead, the default parameter set (36P) was used no matter what.
We will still want to either output the selected regressors in a file _or_ combine the confound loading and confound description generation code in one step, so there isn't any chance of undocumented mismatch between them in the future. That will have to go in a separate PR though.
- Make parameter string a required argument in `load_confound_matrix`.
- Connect the parameter string to the regression node.
- Feed the parameter string to `load_confound_matrix` within the regression node.
=> Use user-requested parameters in regression

.circleci/CiftiWithFreeSurferTest.sh, xcp_d/utils/concatenation.py, xcp_d/utils/plot.py
Closes #620.
- Cut executive summary carpet plot figure sizes in half. The ratios are the same, so, unless there are hardcoded font sizes, it should be fine.
- Remove step in executive summary where DVARS time series are reduced to be the same length across files. @kahinimehta's fix in #614 should mean that code is unnecessary.
- Add logging messages to concatenation code.
None.
=> Reduce executive summary figure size

.circleci/NiftiWithoutFreeSurferTest.sh, .circleci/nifti_without_freesurfer_outputs.txt, docs/output.rst, xcp_d/cli/run.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py, xcp_d/workflow/outputs.py
Closes #615.
- Only run ALFF workflow and save ALFF outputs if bandpass filter is enabled. This will allow users to use the `--disable-bandpass-filter` parameter without breaking xcpd.
The output documentation.
=> Only generate ALFF derivatives if bandpass filtering is enabled

.circleci/config.yml, .circleci/get_data.sh
Closes #337.
- Eliminate duplicated test data by downloading the data in a step _before_ the actual tests.
- Keep data saved in a long-term cache.
None
=> Cache the downloaded test data

setup.cfg
I must have made a mistake in handling merge conflicts between #606 and #607, because somehow brainsprite and tempita were added back as dependencies.
=> Remove brainsprite and tempita from requirements

.circleci/CiftiWithFreeSurferTest.sh, xcp_d/utils/concatenation.py
Solves part of #631.
@smeisler reported two bugs in #631:
1. On a first run, concatenated outlier files were longer than the concatenated data. For two runs of 420 volumes, the concatenated BOLD data had 840 volumes, as expected, while the concatenated outliers had 2520 (3x the expected amount).
- I haven't been able to reproduce this problem so far.
2. On a second run, the concatenated files were collected along with the run-wise files, and were then added into the new concatenated files, resulting in files that are 2x longer than they should be.
- This should be solvable by requiring a run entity in the files being grabbed for concatenation. I've added this in 45bcf5ef91f5d5e10262d11908368a40789249f4. Okay, it was a bit harder to resolve than I thought, but it seems okay as of …
=> Do not merge in concatenated files when re-running concatenation workflow

xcp_d/interfaces/ants.py, xcp_d/interfaces/c3.py, xcp_d/interfaces/filtering.py, xcp_d/interfaces/prepostcleaning.py, xcp_d/interfaces/qc_plot.py, xcp_d/interfaces/regression.py, xcp_d/interfaces/report.py, xcp_d/interfaces/resting_state.py, xcp_d/interfaces/surfplotting.py, xcp_d/interfaces/workbench.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py
Closes None.
- For non-File, non-Directory traits, remove the `exists` parameter. This shouldn't be used.
- Try to ensure that any Files that must exist have `exists=True`.
- Allow custom confounds to be None, and do not coerce it to a string.
None
=> Start to standardize interface parameter calls

xcp_d/utils/plot.py
Closes #653.
Templateflow's BIDSLayout config file uses "density" instead of "den" and "resolution" instead of "res". Other entities are the same between templateflow and pybids/xcpd.
- Map "den" to "density" and "res" to "resolution" for templateflow get call.
None
=> Map abbreviated entities to full names for templateflow get call

.circleci/NiftiWithFreeSurferTest.sh, xcp_d/interfaces/surfplotting.py, xcp_d/utils/concatenation.py, xcp_d/utils/plot.py, xcp_d/workflow/execsummary.py
This stems from https://neurostars.org/t/question-about-xcp-d/23945/8. It looks like dummyscans (dummytime / TR) is treated as a float in PlotSVGData, which (I think) breaks indexing.
- Make `dummyscans` input to `PlotSVGData` an integer, instead of a float.
- Drop `dummyscans` along time axis, rather than space axis, in raw data within `PlotSVGData`.
- Drop `dummyscans` if > 0, not > 1, in `PlotSVGData`.
None
=> Ensure `dummyscans` is an integer in PlotSVGData

.circleci/CiftiWithFreeSurferTest.sh, .circleci/Nibabies.sh, .circleci/NiftiWithoutFreeSurferTest.sh, .circleci/nibabies_outputs.txt, .circleci/nifti_with_freesurfer_outputs.txt, xcp_d/cli/run.py, xcp_d/data/reports.yml, xcp_d/interfaces/report_core.py, xcp_d/interfaces/surfplotting.py, xcp_d/utils/concatenation.py, xcp_d/utils/plot.py, xcp_d/workflow/base.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py, xcp_d/workflow/execsummary.py
Closes #565 and paves the way for #645.
**The breaking changes are: (1) the executive summary is no longer generated by default, (2) the DCAN HDF5 files are not generated by default when concatenation is performed, and (3) the segmentation plot is no longer a brainsprite by default.**
We still need to build in a way for the DCAN team to generate their own brainsprite, which uses a bash script.
- Create a new `--dcan-qc` flag. If set, DCAN HDF5 files, the segmentation brainsprite, and the executive summary will be created.
=> Add `--dcan-qc` flag

xcp_d/interfaces/prepostcleaning.py
In RemoveTR, the step that removes dummy volumes from custom confounds files was actually only _retaining_ the dummy volumes, instead of dropping them.
Drop dummy volumes, instead of keeping _only_ dummy volumes, in custom confounds file.
=> Remove dummy volumes from custom confounds files

.circleci/CiftiWithFreeSurferTest.sh, xcp_d/interfaces/surfplotting.py, xcp_d/utils/concatenation.py, xcp_d/utils/modified_data.py, xcp_d/utils/plot.py
Currently, the concatenation workflow removes dummy volumes from the beginning of the concatenated preprocessed BOLD data within `plot_svgx`. This misses the dummy volumes at the beginning of each run after the first, as they are buried in the middle of the concatenated time series.
- Add a `dummy_scans` parameter to `_concatenate_niimgs`.
- Create a new function, `_drop_dummy_scans`, to remove dummy volumes from BOLD files. This will be used by both `RemoveTR` (in the main workflow) and `_concatenate_niimgs` (in the concatenation workflow, with `--dcan-qc` enabled).
- Only concatenate preprocessed files, calculate preprocessed and post-processed data DVARS, and flag segmentation and mask files, if `dcan_qc` is enabled.
- Remove dummy volumes from preprocessed DVARS.
- Mask the pre- and …
=> Remove dummy volumes from beginning of each run in concatenation workflow

.circleci/tests/test_FD.py, .circleci/tests/test_Reg.py, .circleci/tests/test_TR.py, .circleci/tests/test_confounds.py, xcp_d/interfaces/prepostcleaning.py, xcp_d/interfaces/regression.py, xcp_d/utils/confounds.py, xcp_d/utils/utils.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py
Here's what I'm thinking. We currently load the custom confounds, drop dummy volumes from the custom and fMRIPrep confounds, censor the custom and fMRIPrep confounds, then select the desired regressors from the confounds and combine the two files. This means that, when we get around to selecting regressors, we are no longer working on the original fMRIPrep confounds file, so we need the BOLD file to find the confounds' metadata. This is suboptimal, because it's another place where we are splitting up filenames and hardcoding entities to find new files. 
Instead, I want to select and consolidate our regressors at the beginning of the workflows, then remove dummy volumes and censor the files _afterwards_. This allows us to simplify the confound-selection code considerably, since we no …
=> Consolidate confounds at beginning of denoising workflows

xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py
Closes None. The outputnodes are not currently used, and I'd rather simplify the code than keep them around.
- Remove output node from nifti postprocessing workflow.
- Remove output node from cifti postprocessing workflow.
=> Remove unused outputnodes from nifti and cifti workflows

xcp_d/utils/confounds.py
Closes #669.
- Retain noise components instead of signal components when loading AROMA confounds.
=> Retain noise components instead of dropping them in load_aroma

.circleci/NiftiWithoutFreeSurferTest.sh, docs/workflows.rst, xcp_d/interfaces/qc_plot.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py, xcp_d/workflow/outputs.py, xcp_d/workflow/plotting.py, xcp_d/workflow/postprocessing.py, xcp_d/workflow/restingstate.py
- Create new workflows submodule, `plotting`, with `init_qc_report_wf` function. This function generates the censoring plot, the QC plots, and the QC file.
- Use the new function in both the nifti and cifti postprocessing workflows.
- The new workflow's API.
=> Move QC/censoring plots into new workflow

docs/workflows.rst, xcp_d/utils/bids.py, xcp_d/workflow/base.py, xcp_d/workflow/cifti.py, xcp_d/workflow/execsummary.py, xcp_d/workflow/plotting.py
Partially addresses #684.
- Set MNIInfant as the highest-priority space for nibabies volumetric data.
- Remove `xcp_d.workflow.execsummary.t1_to_native` in favor of `xcp_d.utils.utils.t12native`. The code is the same.
- Remove unnecessary `mni_to_t1w` input from `init_ciftipostprocess_wf` to `init_qc_report_wf`. This input is only used for non-CIFTI data, so there's no point in feeding it in from the CIFTI workflow.
None
=> Use input_type to determine order of preferred spaces

xcp_d/utils/bids.py, xcp_d/utils/utils.py, xcp_d/workflow/execsummary.py
Partially addresses #684, along with #688.
- Use the `from` entity in the `mni_to_t1w` transform filename to determine the template space (and possibly cohort) when selecting the appropriate nifti BOLD file and BOLD reference file for the executive summary. This should only take effect when using both `--cifti` and `--dcan-qc`, and should only _matter_ when there are multiple output spaces in the derivatives.
- Break up a number of function calls in the executive summary workflow into nodes.
- Create a new function, `_find_nifti_files`, that grabs the appropriate nifti files.
None.
=> Infer volumetric space from transform in executive summary with cifti data

.circleci/tests/test_conn.py, docs/usage.rst, xcp_d/cli/run.py, xcp_d/utils/bids.py, xcp_d/utils/doc.py, xcp_d/utils/utils.py, xcp_d/workflow/anatomical.py, xcp_d/workflow/base.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py, xcp_d/workflow/connectivity.py, xcp_d/workflow/execsummary.py, xcp_d/workflow/plotting.py
Closes #685 and closes #591.
- Add `--bids-filter-file` parameter to CLI.
- Change `mni_to_t1w` throughout package to `template_to_t1w`.
- Change `t1w_to_mni` throughout package to `t1w_to_template`.
https://xcp-d--686.org.readthedocs.build/en/686/usage.html#filtering-inputs-with-bids-filter-files
=> Add `--bids-filter-file` parameter

docs/generalworkflow.rst, xcp_d/utils/confounds.py
Nilearn's load_confounds requires users to provide the `desc-smoothAROMAnonaggr_bold` file in order to use the "full" ICA AROMA confounds. Since we provide the regular, preprocessed BOLD file, the "full" confounds will fail.
_However_, by loading the AROMA motion components and using those in our design matrix, we are performing "aggressive" denoising, which is not good. Basically, this PR fixes a loading bug, but commits (temporarily) to a subpar denoising strategy. I plan to switch to another strategy (e.g., non-aggressive or orthogonalization) in a future PR.
- Change the ica_aroma regressor flag from "full" to "basic".
generalworkflow.rst
=> Load basic AROMA confounds

xcp_d/utils/bids.py
Related to #684.
- When using the `--cifti` flag, find the best volumetric space for the `template_to_t1w_xform` and `t1w_to_template_xform` files based on both the preferred spaces and what nifti BOLD files are available. This way, the transforms won't default to MNI152NLin6, the transforms for which are generated automatically, even when it's not an output space. In situations where it's _not_ an output space, the transforms for it were being selected, but then the volumetric BOLD file in another space was selected elsewhere, raising an exception.
- Tangentially, I also fixed a bug in `collect_data` where "bold"["space"] in the filter file was not respected (and indeed raised an exception).
None.
=> Select best volumetric space even when using `--cifti` flag

.circleci/tests/test_prepostcleaning.py, xcp_d/interfaces/prepostcleaning.py, xcp_d/utils/modified_data.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py
Closes #422.
To do:
- Create new function, `xcp_d.utils.modified_data.downcast_to_32`. This function should downcast a nifti or cifti image with either int64 (or higher) or float64 (or higher) to int32 or float32, respectively.
- Create new interface, `xcp_d.interfaces.prepostcleaning.ConvertTo32`. This interface takes specific files in, and downcasts them, as needed, to 32-bit.
- Integrate `ConvertTo32` into nifti and cifti postprocessing workflows.
=> Downcast >32-bit files to 32-bit

.circleci/tests/test_ALFF.py, xcp_d/interfaces/resting_state.py, xcp_d/interfaces/workbench.py, xcp_d/utils/filemanip.py, xcp_d/utils/write_save.py, xcp_d/workflow/postprocessing.py, xcp_d/workflow/restingstate.py
Closes #687.
- Collect cifti extensions and associated intent codes from https://www.nitrc.org/forum/attachment.php?attachid=333&group_id=454&forum_id=1955, and add these to a dictionary in `write_ndata`.
- Select the appropriate cifti intent code base on the output filename's extension in `write_ndata`.
None
=> Use appropriate intent codes for cifti outputs

docs/conf.py, docs/generalworkflow.rst, docs/usage.rst, xcp_d/data/boilerplate.bib, xcp_d/interfaces/regression.py, xcp_d/utils/bids.py, xcp_d/utils/confounds.py, xcp_d/utils/utils.py, xcp_d/workflow/base.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py
Closes #694.
- Mean-center and detrend confounds to match the processing done to the BOLD data, prior to regression.
- Adopt non-aggressive denoising strategy by (1) loading signal AROMA components into design matrix along with noise ones, (2) fitting GLM to all regressors (including signal components), and (3) removing the fitted _nuisance_ regressors from theta to denies it.
- Convert if/else statements in `load_confound_matrix` and `describe_regression` to dictionaries of keyword arguments.
- https://xcp-d--697.org.readthedocs.build/en/697/usage.html#signal-confounds-for-non-aggressive-denoising
=> Enable non-aggressive denoising with signal regressors

xcp_d/utils/concatenation.py
Fixes a bug detected in #698.
- Limit concatenation to runs that have motion files. This should allow the concatenation code to work with the bids-filter-file.
None
=> Only concatenate processed runs

xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py, xcp_d/workflow/plotting.py
Fixes a bug detected in #698.
- Use files from the inputnode, instead of downcast_data, when those files are used as name sources.
None
=> Do not use downcasted files as name sources

xcp_d/workflow/execsummary.py, xcp_d/workflow/plotting.py
Closes #728 and stems from #721.
- Fix a bug in the NIFTI executive summary, where the segmentation file used for the carpet plots was in MNI152NLin2009cAsym space, but transforms from MNI152NLin6Asym were used. I've tacked on the MNI152NLin2009cAsym --> MNI152NLin6Asym transform, to get the dseg from MNI152NLin2009cAsym space to the BOLD space.
None.
=> Warp segmentation file to appropriate space for carpet plots

xcp_d/interfaces/surfplotting.py, xcp_d/utils/bids.py, xcp_d/utils/plot.py, xcp_d/workflow/base.py, xcp_d/workflow/bold.py, xcp_d/workflow/cifti.py, xcp_d/workflow/execsummary.py, xcp_d/workflow/plotting.py
Closes None.
Open questions:
- When would we want to warp the T1w image to standard space? At the moment, we collect the native T1w-space image, but we should really collect the standard-space one as well and just save that to the output directory. When would there be BOLD data in standard space, but not a T1w image in the same space?
- We don't support native or T1w-space inputs/outputs, so do we need to support warps to T1w or native space?
Resolved questions:
- Should we just use the dseg in the preprocessing derivatives?
- There should be a standard-space tissue-type dseg in the fMRIPrep derivatives, in the anat folder. **However, this dseg is just the three tissue types, I believe, while the carpet plot uses labels like subcortical GM and cerebellum.**
- I assume that Nibabies …
=> Refactor executive summary workflow

.circleci/tests/test_conn.py, xcp_d/interfaces/connectivity.py, xcp_d/utils/fcon.py, xcp_d/workflow/bold.py, xcp_d/workflow/connectivity.py
Closes None, but is related to #700.
I tested out using the mask vs. not, and using the mask means that any voxels outside the mask will be excluded before the mean time series is calculated for each region. If we don't use the mask, then those voxels (in the atlas, but outside the mask) are replaced with zeros.
- Use the downsampled brain mask in the NiftiLabelsMasker.
None.
=> Use brain mask in NIFTI connectivity workflow

xcp_d/cli/run.py
Closes #674.
- Copy sentry logging from qsiprep, in order to log the start of the workflow.
None.
=> Track start of workflow with sentry

.circleci/config.yml
Closes None.
- Use a DockerHub access token instead of a password, and change the secrets we use.
None.
=> Change secret keys for deploying to DockerHub

setup.cfg
Closes None, but addresses issue with networkx >=3 that's breaking our tests.
- Pin networkx version to 2.8.8. We can increase this when we increase the nipype version as well.
=> Pin networkx version

.circleci/tests/test_prepostcleaning.py
Closes #696. As it turns out, the reason the test was failing wasn't due to any issue with storing float64s or int64s in CIFTI files- it was just that I was using the wrong extensions in the test files!
- Change "CIFTI" test files from `.nii.gz` extension (nifti) to `.dtseries.nii` (cifti).
- Stop skipping the CIFTI downcasting test.
=> Fix CIFTI downcasting test

xcp_d/data/nipreps.json, xcp_d/tests/data/ds001419-fmriprep_nifti_outputs.txt, xcp_d/tests/data/nibabies_outputs.txt, xcp_d/tests/data/nifti_without_freesurfer_outputs.txt, xcp_d/tests/test_utils_bids.py, xcp_d/utils/bids.py, xcp_d/workflow/anatomical.py, xcp_d/workflow/base.py
Maybe, hopefully, addresses #701.
- Rename `init_t1w_wf` to `init_warp_anats_to_template_wf`.
- Add tests for `xcp_d.utils.bids.collect_data`.
- Only search for to-MNI152Nlin6Asym transform when the inputs are CIFTIs, since this is the associated volumetric space for the fsLR CIFTI template.
- Extract the appropriate template to warp to in the T1w workflow from the transforms that are provided.
- Change the template's resolution from 2mm to 1mm in the T1w workflow.
=> Select MNI152NLin6Asym target space for T1w from CIFTI derivatives

docs/usage.rst
Closes #749.
- Add link to the new examples repository in the documentation.
- usage.rst
=> Link to `xcp_d-examples` in documentation

xcp_d/workflow/base.py
Closes None. I'm not sure how this slipped past me, but the brainsprite workflow should only be run when `--dcan_qc` is included.
- Make `brainsprite_wf` dependent on `dcan_qc`.
=> Only generate brainsprite figures when the `--dcan_qc` flag is used

.circleci/config.yml, docs/output.rst, xcp_d/interfaces/qc_plot.py
Closes None.
- Show the test logs for the workflow tests live. This way we can see what's happening like we could before #740.
- Add the atlas filename patterns to the outputs file. I forgot to do this in #647.
- Store unit test artifacts in `/src/xcp_d/.circleci/out/`. We can use this to debug tests in the future.
Outputs file.
=> Show workflow test logs live

xcp_d/interfaces/resting_state.py, xcp_d/utils/modified_data.py, xcp_d/utils/plot.py, xcp_d/utils/utils.py, xcp_d/utils/write_save.py
Closes None. Just removing some unused code.
- Remove BrainPlot.
- Remove `z_score_nifti`.
- Remove `scale` parameter from `read_ndata` and `write_ndata`. Move `scalex` to `modified_data` and rename it to `scale_data_min_max`.
=> Remove unused BrainPlot interface

xcp_d/cli/parser_utils.py, xcp_d/cli/run.py, xcp_d/interfaces/connectivity.py, xcp_d/interfaces/prepostcleaning.py, xcp_d/tests/test_cli.py, xcp_d/tests/test_cli_utils.py, xcp_d/tests/test_workflows_connectivity.py, xcp_d/workflows/base.py, xcp_d/workflows/bold.py, xcp_d/workflows/cifti.py, xcp_d/workflows/connectivity.py
Closes #776.
- Add `min_coverage` parameter to the CLI, along with each of the workflows and interfaces that need it.
None.
=> Add `min_coverage` parameter to threshold parcel coverage

xcp_d/interfaces/ants.py, xcp_d/interfaces/connectivity.py, xcp_d/tests/test_workflows_connectivity.py, xcp_d/utils/utils.py, xcp_d/workflows/anatomical.py, xcp_d/workflows/connectivity.py, xcp_d/workflows/plotting.py
I'm not sure how I missed this. Last year, in October, we had conversations on Slack about using GenericLabel over MultiLabel, but somehow this wasn't translated to a PR in xcp_d.
- Use GenericLabel instead of MultiLabel when applying transforms to atlas files.
- Replace miscellaneous uses of `niworkflows.interfaces.fixes.FixHeaderApplyTransforms`, `nipype.interfaces.ants.ApplyTransforms`, and `xcp_d.interfaces.connectivity.ApplyTransformsx` with a new interface inheriting from `niworkflows.interfaces.fixes.FixHeaderApplyTransforms`. The only change to the interface is that I've overridden the allowed interpolation options to allow GenericLabel.
None.
=> Replace MultiLabel interpolation with GenericLabel

xcp_d/utils/confounds.py
Closes #787.
- Document the use of cosine basis regressors in the boilerplate when aCompCor regressors are included.
None
=> Mention cosine regressors in aCompCor boilerplate

.circleci/config.yml, Dockerfile
Closes None, but may help with #793.
- Use the new Docker image.
=> MAINT 0.3.x: Update base Docker image

.circleci/config.yml, Dockerfile
Closes None.
- Change base Docker image to new `pennlinc/xcp_d_build`.
=> Update base Docker image

.circleci/RunPyTests.sh, .circleci/get_data.sh, xcp_d/tests/conftest.py, xcp_d/tests/data/license.txt, xcp_d/tests/test_cli.py
Closes None.
- Remove FreeSurfer license file. We shouldn't have it in the repo.
- Set license environment variable as pytest fixture.
=> Set FreeSurfer license as pytest fixture

xcp_d/cli/run.py
Closes #804.
- Check that a `dataset_description.json` file exists in `fmri_dir` within `build_workflow`. This should catch cases where a user provides the path to the general derivatives folder (e.g., `/dset/derivatives`), rather than the specific preprocessed derivatives (e.g., `/dset/derivatives/fmriprep`).
None.
=> Check for existence of dataset_description.json in fmri_dir

xcp_d/cli/run.py
Closes None, but is related to #714. For HCP/DCAN inputs, a dataset description file won't be available until after the preprocessed data are converted to BIDS format, but the check was occurring _before_ the conversion.
- Move dataset_description check to after HCP/DCAN conversion.
=> Move dataset desc check to after conversion

docs/generalworkflow.rst, xcp_d/data/boilerplate.bib, xcp_d/data/reports.yml, xcp_d/utils/atlas.py, xcp_d/utils/bids.py, xcp_d/utils/confounds.py, xcp_d/utils/execsummary.py, xcp_d/utils/modified_data.py, xcp_d/utils/plotting.py, xcp_d/utils/qcmetrics.py, xcp_d/utils/utils.py
Closes #818, closes #817, and closes #791.
- Add design matrix plot to the nipreps report (#818).
- Remove Jaccard from QC metrics (#817).
- Rename cross-correlation in QC metrics to Pearson correlation.
- Remove surface ALFF and ReHo plots from nipreps report, but keep the volumetric versions (#791).
=> Add design matrix to report

docs/outputs.rst, docs/workflows.rst, xcp_d/cli/run.py, xcp_d/interfaces/prepostcleaning.py, xcp_d/tests/data/ds001419-fmriprep_cifti_outputs.txt, xcp_d/tests/data/ds001419-fmriprep_nifti_outputs.txt, xcp_d/tests/test_cli.py, xcp_d/utils/doc.py, xcp_d/utils/modified_data.py, xcp_d/workflows/bold.py, xcp_d/workflows/cifti.py, xcp_d/workflows/outputs.py, xcp_d/workflows/postprocessing.py
Closes #811 and closes #812.
- Allow `--fd-thresh` to be <=0, in which case censoring will be disabled.
- Only generate ALFF outputs if censoring is disabled.
=> Allow users to disable censoring, and only generate ALFF if censoring is disabled

xcp_d/tests/test_cli.py, xcp_d/workflows/postprocessing.py
In my recent refactor, I must have accidentally broken the connection, so custom confounds were not used in the regression.
- Connect custom confounds to confound consolidation node.
=> Connect custom confounds to confound consolidation node

.circleci/NiftiWithFreeSurferTest.sh, xcp_d/cli/run.py, xcp_d/interfaces/censoring.py, xcp_d/tests/test_cli.py, xcp_d/utils/doc.py, xcp_d/workflows/base.py, xcp_d/workflows/bold.py, xcp_d/workflows/cifti.py
Closes None, but removes a parameter that was deprecated and due to be removed in 0.4.0.
- Remove dummytime.
=> Remove deprecated `--dummytime` parameter

docs/workflows.rst, xcp_d/tests/test_workflows_anatomical.py, xcp_d/workflows/anatomical.py, xcp_d/workflows/base.py, xcp_d/workflows/outputs.py
- Move the HCP-style surface generation step from `init_warp_surfaces_to_template_wf` to `init_postprocess_surfaces_wf`.
- Only call `init_warp_surfaces_to_template_wf` if the surfaces need to be warped to fsLR. Otherwise, just pass them to `init_copy_inputs_to_outputs_wf`.
- Rename `init_postprocess_anat_wf` to `init_postprocess_surfaces_wf`. This workflow no longer handles the anatomical executive summary plots or the volumetric anatomical images.
- Rename `init_warp_anats_to_template_wf` to `init_postprocess_anat_wf`. This workflow handles the anatomical executive summary plots and the volumetric anatomical images.
=> Simplify the anatomical workflow some more

setup.cfg, xcp_d/tests/test_confounds.py, xcp_d/utils/confounds.py, xcp_d/workflows/postprocessing.py
Closes #849.
- If `load_confounds` can't find compcor regressors, use a custom function to find them and add them to the other confounds load_confounds found.
=> Work around load_confounds aCompCor bug

xcp_d/tests/data/nibabies_outputs.txt, xcp_d/tests/test_cli.py, xcp_d/workflows/postprocessing.py
Closes #859. I probably introduced this bug in my recent round of refactors.
- Only run the smoothing workflow if the smoothing kernel is > 0.
=> Allow for smoothing to be zero

xcp_d/cli/run.py, xcp_d/tests/test_cli.py, xcp_d/utils/doc.py, xcp_d/utils/utils.py, xcp_d/workflows/outputs.py, xcp_d/workflows/postprocessing.py
Closes #844. Happy to work on this a bit. Was wondering if you think it would be better to have a separate flag for disabling  the filter components, or rather do something like "set `--lower-bpf` to 0 to disable" (or something else)? What I have begun drafting so far uses a "set to 0" approach.
Can ALFF be run on data that has only been low-passed?
=> Support high-pass or low-pass only filtering

docs/usage.rst, xcp_d/cli/run.py
Closes #873.
- Expand help message for `--task-id` pointing toward `--bids-filter-file`.
=> Document how to process multiple, but not all, tasks

docs/outputs.rst, docs/workflows.rst, xcp_d/cli/run.py, xcp_d/interfaces/report_core.py, xcp_d/tests/data/ds001419-fmriprep_nifti_outputs.txt, xcp_d/tests/test_cli.py
Closes #875.
- Generate the executive summary even when `--dcan-qc` isn't used.
=> Always generate the DCAN executive summary

xcp_d/interfaces/ants.py
Closes None.
- Currently, ApplyTransforms overwrites the output image input no matter what. This change uses that input for the output filename, but only when it is provided. This shouldn't affect anything in XCP-D, since XCP-D relies on the auto-generated output filename, but it makes it easier to use ApplyTransforms elsewhere.
=> Use output path when provided in ApplyTransforms interface

xcp_d/interfaces/workbench.py, xcp_d/utils/dcan2fmriprep.py, xcp_d/utils/hcp2fmriprep.py, xcp_d/utils/ingestion.py, xcp_d/workflows/connectivity.py
Hopefully fixes #923. 
- Convert GIFTI morphometry files to CIFTIs as part of ABCD/HCP ingression.
- Use `out_file` input to set the output filename for `CiftiCreateDenseScalar` when provided.
- Account for multi-session ABCD anatomical data.
=> Correct ABCD/HCP surface ingression

xcp_d/tests/test_workflows_anatomical.py, xcp_d/workflows/anatomical.py, xcp_d/workflows/base.py, xcp_d/workflows/bold.py, xcp_d/workflows/cifti.py, xcp_d/workflows/plotting.py
Closes none, but related to #933.
Even though the executive summary is generated no matter what, the actual figures that go into are not currently being created if `--dcan-qc` isn't used. This PR creates most of the executive summary's figures no matter what.
=> Generate executive summary figures without `--dcan-qc`

xcp_d/data/executive_summary_templates/executive_summary.html.jinja, xcp_d/data/executive_summary_templates/task_static_plots.html.jinja, xcp_d/interfaces/execsummary.py
Closes #938 and closes #940.
- Fix the description entity in the postprocessing carpet plot's query in the executive summary.
- Sort task file entities for the executive summary.
- Previously, only the task name and run number were used to sort the task section.
- Build the task section names from task and run entities, along with any entities that are not constant across all of the subject's BOLD runs. This should help with datasets like the mobile-phenomics pilot, where single-echo and multi-echo runs are dissociated with the `acq` entity.
- Skip the final task section (carpets + mean BOLD + boldref + registration plots) for concatenated resting-state data, since (1) there's a section higher up for the concatenated resting-state carpets and (2) there are no mean BOLD, bolref, or …
=> Fix resting-state plots in executive summary

.github/workflows/lint.yml, pyproject.toml
Closes none, but addresses a problem that came up today.
- Remove flake8-warnings from our dependencies.
=> Remove `flake8-warnings` from dependencies

xcp_d/utils/hcp2fmriprep.py
Closes #951.
- Use a regular expression to split the HCP task name into a task entity and a run entity.
- For example, `REST1` becomes `task-rest_run-1`.
=> Split HCP tasks into task and run entities

xcp_d/tests/test_utils_bids.py, xcp_d/utils/bids.py, xcp_d/workflows/base.py, xcp_d/workflows/concatenation.py
Closes none. This will primarily (only?) affect HCP data, which acquires fMRI runs with both run entities and dir entities. The acquisition order is counterbalanced, so we can't ensure that the data will be concatenated in the right order, but it should still be an improvement.
- Concatenate BOLD data across run and dir entities.
- Sort the files first by run, then by direction.
- This is because HCP acquires run 1 in session 1 and run 2 in session 2. The order of directions (LR and RL) is counterbalanced, but run is consistent. Therefore we can't guarantee that LR --> RL is right (it'll be right for one run, but not the other), but we _can_ guarantee that run 1 --> run 2.
=> Concatenate across directions as well as runs

docs/workflows.rst, pyproject.toml, xcp_d/tests/test_cli.py, xcp_d/tests/test_utils_utils.py, xcp_d/utils/utils.py
Closes #949.
- After interpolation, but before bandpass filtering, replace any interpolated volumes at the beginning or end of the run with the closest non-outlier volume's data. This should act much like the `constant` buffer we use for the bandpass filter.
=> Don't interpolate volumes at beginning/end of run

.github/workflows/lint.yml, docs/workflows.rst, pyproject.toml, xcp_d/data/executive_summary_templates/executive_summary.html.jinja, xcp_d/data/executive_summary_templates/task_static_plots.html.jinja, xcp_d/interfaces/execsummary.py, xcp_d/interfaces/plotting.py, xcp_d/interfaces/report.py, xcp_d/tests/test_cli.py, xcp_d/tests/test_utils_bids.py, xcp_d/tests/test_utils_utils.py, xcp_d/utils/bids.py, xcp_d/utils/hcp2fmriprep.py, xcp_d/utils/qcmetrics.py, xcp_d/utils/utils.py, xcp_d/workflows/base.py, xcp_d/workflows/concatenation.py
Closes none.
- Reproduce #952, #947, #955, #941, #965, #950, #958 for 0.5.1 (paper) release.
=> Reproduce recent changes for 0.5.1

xcp_d/interfaces/plotting.py, xcp_d/interfaces/report.py, xcp_d/utils/qcmetrics.py
Closes #957.
I'd _really_ love to also change the extension from `csv` to `tsv`, for BIDS compatibility. I guess I'll wait until a later release for that part.
- Rename LINC QC metrics to follow snake case, per BIDS recommendation.
- `meanFD` --> `mean_fd`
- `relMeansRMSMotion` --> `mean_relative_rms`
- `relMaxRMSMotion` --> `max_relative_rms`
- `meanDVInit` --> `mean_dvars_initial`
- `meanDVFinal` --> `mean_dvars_final`
- `nVolsRemoved ` --> `num_dummy_volumes`
- `motionDVCorrInit` --> `fd_dvars_correlation_initial`
- `motionDVCorrFinal` --> `fd_dvars_correlation_final`
- `num_censored_volumes` stays the same.
- `coregDice` --> `coreg_dice`
- `coregPearson` --> `coreg_correlation`
- `coregCoverage` --> `coreg_overlap`
- `normDice` --> `norm_dice`
- `normPearson` --> `norm_correlation`
- …
=> Update the QC metrics

xcp_d/interfaces/censoring.py, xcp_d/tests/data/test_ds001419_cifti_outputs.txt, xcp_d/tests/data/test_ds001419_nifti_outputs.txt, xcp_d/tests/data/test_fmriprep_without_freesurfer_outputs.txt, xcp_d/tests/data/test_nibabies_outputs.txt, xcp_d/tests/data/test_pnc_cifti_outputs.txt, xcp_d/tests/data/test_pnc_nifti_outputs.txt, xcp_d/tests/test_confounds.py, xcp_d/tests/test_interfaces_censoring.py, xcp_d/tests/test_utils_utils.py, xcp_d/utils/confounds.py, xcp_d/utils/utils.py, xcp_d/workflows/bold.py, xcp_d/workflows/cifti.py, xcp_d/workflows/outputs.py, xcp_d/workflows/postprocessing.py
Closes #974.
- Extract column-specific metadata from the fMRIPrep confounds file.
- Move confound orthogonalization from the denoising workflow to the confounds preparation workflow.
- Retain the orthogonalized confounds (with `_orth` appended to the column names) in the output confounds file.
=> Retain orthogonalized confounds

xcp_d/interfaces/connectivity.py, xcp_d/workflows/connectivity.py
Related to https://github.com/PennLINC/informatics_misc/issues/93.
- Request 15 * the image size for functional connectivity node memory (up from 5 * image size).
- Use `gc.collect()` to remove objects as they stop being used in the functional connectivity nodes.
=> Try to reduce memory requirements of functional connectivity nodes

xcp_d/cli/run.py, xcp_d/tests/test_cli_run.py
Closes #993.
- Dont override motion filtering parameters when `--fd-thresh <= 0`.
=> Allow motion filtering when motion-based censoring is disabled

xcp_d/interfaces/workbench.py, xcp_d/workflows/connectivity.py
Closes #997.
- Change atlas CIFTIs to dscalars after resampling them to the data CIFTI's resolution, but before parcellating them. This produces a valid pscalar file, which can then be used to produce a valid coverage CIFTI (also a pscalar file).
=> Fix coverage CIFTIs

xcp_d/interfaces/concatenation.py, xcp_d/tests/conftest.py, xcp_d/tests/test_interfaces_concatenation.py, xcp_d/tests/test_utils_utils.py, xcp_d/utils/bids.py, xcp_d/utils/dcan2fmriprep.py, xcp_d/utils/doc.py, xcp_d/utils/hcp2fmriprep.py, xcp_d/utils/utils.py, xcp_d/workflows/base.py, xcp_d/workflows/bold.py, xcp_d/workflows/cifti.py, xcp_d/workflows/concatenation.py, xcp_d/workflows/plotting.py
Closes #1002. This is a necessary change for fMRIPrep 23.2.0 compliance.
- Remove collection of anat-to-native transform, which led to #1002 when fMRIPrep changed their naming convention. The transform was never actually used for anything.
- Remove any unreachable code that ostensibly supported native-space BOLD data.
=> Remove unused native-space support

xcp_d/interfaces/connectivity.py, xcp_d/interfaces/plotting.py, xcp_d/tests/test_utils_execsummary.py, xcp_d/utils/plotting.py
Closes #627.
- Add a colorbar to the volumetric ALFF and ReHo plots.
- Close figures after saving them to prevent bleedover.
=> Add colorbar to ALFF and ReHo plots

docs/workflows.rst, xcp_d/utils/restingstate.py, xcp_d/workflows/restingstate.py
Related to #1032.
- Calculate the SD of the denoised BOLD data, then multiply the ALFF computed on the scaled BOLD data by that SD. This brings ALFF back to its original scale, and the censored version of ALFF will has the same scale as the uncensored version.
=> Rescale ALFF based on original BOLD standard deviation

xcp_d/interfaces/concatenation.py
Closes #999.
- Remove the `dir` entity from concatenated filenames.
=> Drop `dir` entity from concatenated filenames

xcp_d/tests/test_utils_write_save.py, xcp_d/utils/write_save.py
Closes #1035.
- Fix a bug in `xcp_d.utils.write_save.write_ndata()`, in which all CIFTIs were written out with a SeriesAxis. In the fixed version, `.dtseries.nii` files have a SeriesAxis and a BrainModelAxis (same as before), but `.dscalar.nii` files have a _ScalarAxis_ and a BrainModelAxis. Other extensions aren't supported yet, but there shouldn't be any cases in XCP-D where we use `write_ndata` to write out any other types of CIFTI.
=> Fix dscalar CIFTI generation

xcp_d/cli/run.py
Related to #1041.
- Add `--stop-on-first-crash` option, which is fed into the Nipype configuration.
=> Add `--stop-on-first-crash` option to command-line interface

xcp_d/cli/run.py
Formerly, for `--smoothing`:
> This may be set to 0.
Such piece of description is a little confusing although one might think smoothing is probably disabled in that case. It could be clearer and more consistent with the description of other parameters, such as `--min-time`, by clearly stating:
> Set to 0 to disable smoothing.
Make the description clearer.
None.
=> Make description of `smoothing` parameter clearer when set to `0`

xcp_d/utils/atlas.py
Closes #1064.
- Skip writing out the atlas file if it already exists in the atlases subfolder.
=> Fix potential atlas file race condition

xcp_d/utils/bids.py, xcp_d/workflows/connectivity.py
Closes none, but addresses an issue reported in https://neurostars.org/t/xcp-d-dataset-type-key-error/28385.
- Raise a warning if "DatasetType" is not defined in the preprocessing derivatives' `dataset_description.json`.
- Raise an informative error if "DatasetType" is "raw" in the preprocessing derivatives' `dataset_description.json`.
=> Make "DatasetType" key recommended, not required

xcp_d/cli/run.py
Closes #1055.
- If `--fd-thresh` is set to 0 (disabling censoring) and `--min-time` is set to 0 (no longer limiting the run duration), don't warn users about `--min-time` being disabled.
=> Do not warn if `fd-thresh` and `min-time` are both set to 0

xcp_d/tests/test_utils_atlas.py, xcp_d/utils/atlas.py, xcp_d/workflows/connectivity.py
Closes #1064.
- Switch from using DerivativesDataSink to using `xcp_d.utils.atlas.copy_atlas` for writing out the atlas-specific TSV and JSON files.
- Modify `copy_atlas` to handle TSV and JSON files.
- Update associated test.
=> Use `copy_atlas` to write out atlas tsv and json files

xcp_d/cli/run.py, xcp_d/tests/test_cli_run.py, xcp_d/tests/utils.py
Related to #1067.
- If `--fs-license-file` is not set, then the environment variable `FS_LICENSE` must be defined. This checks that that environment variable is set, and that the variable points to an existing file.
=> Raise error if FS_LICENSE environment variable is not an existing file

xcp_d/workflows/execsummary.py
Closes none, but addresses a bug identified by @erikglee and @tjhendrickson. The line that selects either T1w, T2w, or both based on what's available was wrong, and was only selecting the T2w when the T1w wasn't available.
- Fix lines that select which anatomical modalities to use for executive summary plots.
=> Generate T2w executive summary plots when T1w is also available

xcp_d/tests/test_utils_bids.py, xcp_d/utils/bids.py
Closes #1080.
- Change the internal XCP-D BIDS URI prefix from `bids:xcp_d:` to `bids::`.
- Remove the `xcp_d` DatasetLink from the dataset_description.json. There's no need to include a link from the dataset to itself.
=> Replace `bids:xcp_d:` BIDS URI with `bids::`

xcp_d/cli/run.py, xcp_d/interfaces/execsummary.py, xcp_d/tests/test_utils_bids.py, xcp_d/tests/utils.py, xcp_d/utils/bids.py
References #1090.
- Ensure that the `queries` dictionary has the necessary keys for error reporting in `collect_mesh_data`.
- Drop `derivatives=True` from BIDSLayout inits. This will resolve a number of warnings.
=> Fix query error report in `collect_mesh_data`

xcp_d/tests/test_utils_confounds.py
The pytests step is failing in the 0.7.1rc1 release's CircleCI workflow. For some reason, warning capture started failing.
```
FAILED xcp_d/tests/test_filtering.py::test_motion_filtering_lp - Failed: DID NOT WARN. No warnings of type (<class 'Warning'>,) were emitted.
Emitted warnings: [].
FAILED xcp_d/tests/test_filtering.py::test_motion_filtering_notch - Failed: DID NOT WARN. No warnings of type (<class 'UserWarning'>,) were emitted.
Emitted warnings: [ DeprecationWarning('Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)')].
FAILED xcp_d/tests/test_utils_bids.py::test_collect_participants - Failed: DID NOT WARN. No warnings of type …
```
=> Investigate test failures

pyproject.toml, xcp_d/config.py
References #1106 (won't be able to tell if it works until I make a release, I think).
- Add `pytest-env` to testing dependencies.
- Set environment variable `PYTHONWARNINGS` to "default" in test runs, since it is set to "ignore" for production runs by the Config object.
=> Use pytest-env to capture warnings on CI runs

xcp_d/interfaces/connectivity.py
Meant to address the many warnings I'm seeing:
```
xcp_d/tests/test_cli.py::test_ds001419_cifti
/src/xcp_d/xcp_d/interfaces/connectivity.py:476: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.48340796876794123' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
coverage_df.loc[parcel_label, "coverage"] = parcel_coverage
```
=> Convert coverage values to float32 to address pandas warning

xcp_d/interfaces/censoring.py, xcp_d/tests/test_utils_confounds.py, xcp_d/utils/confounds.py, xcp_d/utils/modified_data.py, xcp_d/workflows/bold.py, xcp_d/workflows/cifti.py, xcp_d/workflows/postprocessing.py, xcp_d/workflows/restingstate.py
Closes #1113.
- Move the automatic filter parameter modification out of `utils.confounds.motion_regression_filter` and into its own function (`utils.confounds._modify_motion_filter`).
- Split `utils.confounds.describe_censoring` into `describe_censoring` and `describe_motion_parameters`.
- Call the new function (`_modify_motion_filter`) in `utils.confounds.describe_motion_parameters` so that the boilerplate reflects any changes to the motion filter parameters.
- Call `_modify_motion_filter` in `utils.modified_data.flag_bad_run` as well, since `load_motion` doesn't call it anymore.
- Improve spacing (e.g., spaces between sentences and new paragraphs) in the boilerplate.
- Add motion filter parameters to appropriate metadata files.
- Fix up denoising boilerplate to reflect the updated …
=> Modify metadata and boilerplate to reflect updated motion filter parameters

xcp_d/utils/bids.py
Closes none, but fixes a bug found by @kahinimehta.
- Include `subject` in the native-space mesh surface query, which should now match the standard-space mesh surface query (which works), except for the space and den entities.
=> Add "subject" to native-space surface query

xcp_d/ingression/utils.py
Closes none, but hopefully addresses a problem Dhivya Srinivasan identified when processing UK Biobank data.
- Set a run-specific working directory for the NormalizeMotionParams interfaces called by XCP-D in the UK Biobank ingression workflow. This should fix a likely race condition where different runs were writing out and reading from the same file.
=> Use run-specific cwd for UK Biobank ingression interface

xcp_d/config.py, xcp_d/data/xcp_d_bids_config2.json, xcp_d/tests/test_utils_bids.py
Closes none. The BIDSLayout with `bids` and `derivatives` configs was not identifying `cohort`, even though I had `invalid_filters="allow"`. I _thought_ that `invalid_filters="allow"` would let BIDSLayout find any entity-formatted strings in filenames, but apparently that's not true.
- Add a new pybids config file that include `cohort`, but not `datatype` (which conflicts with the existing `datatype` definition).
=> Add third config to BIDSLayout that defines cohort entity

xcp_d/interfaces/execsummary.py, xcp_d/interfaces/plotting.py, xcp_d/utils/confounds.py
Closes #1101 and addresses a request for the manuscript.
- Don't include the not-yet-implemented subcortical figures in the executive summary.
- Set the cut coordinates to (0, 0, 0) (center of FOV) for the BOLD reference images in the executive summary.
- Ignore annoying SettingWithCopyWarnings when calculating motion parameters.
=> Ignore subcortical figures and plot FOV center of reference brains in executive summary

pyproject.toml, xcp_d/interfaces/plotting.py, xcp_d/tests/test_utils_qcmetrics.py, xcp_d/utils/plotting.py, xcp_d/utils/qcmetrics.py
Closes none, but stems from [this NeuroStars post](https://neurostars.org/t/higher-dvars-in-xcp-d-than-fmriprep/29008).
- Replace XCP-D's DVARS formula with the one from Nipype/fMRIPrep.
- I had to remove the intensity-normalization element because it doesn't seem to work appropriately on the denoised data. Basically, the intensity normalization divide by the median value across the brain and across time in the BOLD data, but that median value is very low (~0.01) in the denoised data, which results in infinite values in the denoised DVARS.
- Adopt the "standardized" DVARS from the new function for our QC measures and plots.
=> Use standardized DVARS from Nipype

xcp_d/_warnings.py, xcp_d/config.py, xcp_d/ingression/abcdbids.py, xcp_d/ingression/hcpya.py, xcp_d/ingression/ukbiobank.py, xcp_d/interfaces/bids.py, xcp_d/interfaces/execsummary.py, xcp_d/tests/test_cli.py, xcp_d/tests/test_smoothing.py, xcp_d/tests/test_utils_bids.py, xcp_d/tests/test_utils_execsummary.py, xcp_d/tests/tests.py, xcp_d/utils/atlas.py, xcp_d/utils/doc.py, xcp_d/utils/sentry.py, xcp_d/utils/utils.py, xcp_d/workflows/connectivity.py, xcp_d/workflows/execsummary.py, xcp_d/workflows/postprocessing.py
Closes none.
- Stop loading internal resources with `pkg_resources` (which is deprecated) and start using `xcp_d.data.load`.
=> Replace pkgrf with load_data

.circleci/config.yml, Dockerfile
Closes none, but addresses an odd behavior I'd been noticing where templateflow was downloading templates in my XCP-D runs. This was because the step in the build image where templates are precached was happening _before_ the home directory was redefined, so the ultimate templateflow directory was not where the templates had previously been downloaded!
=> Update to new build image (v0.0.12)

.circleci/config.yml, xcp_d/cli/parser.py, xcp_d/cli/run.py, xcp_d/tests/data/config.toml, xcp_d/tests/test_cli.py, xcp_d/utils/debug.py
Closes none, but addresses a bug reported by @erikglee when running XCP-D on CBRAIN.
- Fix a bug in which I referenced an attribute of the Config object that doesn't exist. I copied the code from fMRIPrep without noticing the problem. The workflow still successfully ran, but the exit code was 1 (failure) instead of 0 (success) regardless.
- Improve integration tests by using `xcp_d.cli.run.main()` directly.
=> Fix exit code bug in `cli.run.main()`

xcp_d/interfaces/concatenation.py, xcp_d/interfaces/execsummary.py, xcp_d/interfaces/plotting.py, xcp_d/utils/plotting.py, xcp_d/workflows/concatenation.py
Closes none, but addresses the following issue identified by @kahinimehta. Basically, when there is a concatenated resting-state run, the executive summary shows it as a regular run in the run-wise BOLD section. However, the only figures available for the concatenated resting-state run (as opposed to a resting-state scan without a run entity) are the carpet plots.
- When compiling the list of files for the BOLD section of the executive summary, if there is a resting-state scan without run or direction entities (indicating that it may be concatenated), check if there are resting-state scans _with_ either run or direction. If there are, then drop the concatenated resting-state scan from the list of files.
=> Drop concatenated rest-as-run section from executive summary

.versions.json, docs/changes.md, xcp_d/cli/parser.py, xcp_d/config.py, xcp_d/tests/test_cli_run.py
Closes #1171.
- Set destination variables for `--upper-bpf` and `--lower-bpf` parameters so that they are passed along to the Config object as `low_pass` and `high_pass`, respectively.
- Flag versions 0.7.1 and 0.7.2 in the version log, as the bandpass filter parameters selected by the user were not respected in those versions.
- Set default values in the Config object to None when feasible, in order to more readily identify bugs like this in the future.
=> Fix band-pass filter settings in Config

.versions.json, docs/changes.md
Closes none, but is related to #1171.
- Add 0.7.3 to the notes from #1172.
=> Add 0.7.3 to changelog and note filtering bug

xcp_d/utils/restingstate.py
Closes none. I noticed that the integration tests with low-pass set to 0 (pnc_cifti and ds001419_cifti) had ALFF maps/TSVs that were all NaNs.
- Set high-pass and low-pass values to the frequency range's appropriate extrema if either is disabled (set to 0).
=> Allow ALFF to work with low-pass or high-pass filters

xcp_d/interfaces/connectivity.py, xcp_d/tests/test_cli.py
Closes #1187.
- In cases where only one atlas is requested, place the `Axes` object for `ConnectPlot` in a numpy array.
=> Fix ConnectPlot

pyproject.toml, xcp_d/reports/core.py
Closes #1200.
- Loop over sessions when generating executive summaries.
- Don't install sphinx-argparse 0.5.0 (copied from https://github.com/nipreps/fmriprep/pull/3325).
=> Generate session-wise executive summaries

xcp_d/utils/bids.py
Closes #1199.
- For T2w-only processing, look for anatomical inputs with either no space entity (current behavior) or space-T2w.
=> Look for space entity in T2w-only anatomical inputs

xcp_d/interfaces/bids.py, xcp_d/interfaces/connectivity.py, xcp_d/tests/conftest.py, xcp_d/tests/test_utils_bids.py, xcp_d/tests/test_workflows_anatomical.py, xcp_d/utils/bids.py, xcp_d/workflows/anatomical.py, xcp_d/workflows/base.py
Closes none.
This is a breaking change for older versions of fMRIPrep and/or Nibabies, when the sphere file was not written out as a BIDS derivative.
- Grab the subject's registration sphere from the BIDS derivatives instead of navigating Freesurfer and/or MCRIBS outputs.
- Use templateflow to grab other spheres necessary to warp mesh files to fsLR.
=> Load spheres for anatomical workflow from TemplateFlow and BIDS derivatives

xcp_d/data/io_spec.yaml
Closes none, but relates to https://github.com/nipreps/fmriprep/commit/ea651967a9427d91124cd7b9238162b409935d4c, https://github.com/nipreps/smriprep/pull/446, and https://github.com/nipreps/nibabies/pull/368. This will probably take effect at Nibabies 24.0.0 and fMRIPrep 24.0.2.
- Accept either no space entity (old/current versions for fMRIPrep and nibabies) or `space-fsaverage` (upcoming versions of fMRIPrep and nibabies) for surface spheres used in the anatomical workflow.
=> Allow `space-fsaverage` for sphere files

docs/workflows.rst, xcp_d/cli/parser.py, xcp_d/tests/test_cli.py, xcp_d/tests/test_cli_run.py
Closes none, but addresses a request by Damien Fair.
- Enable linc-qc for abcd and hbcd modes by default.
- Change `--linc-qc` and `--abcc-qc` to accept `y` or `n` as keywords.
=> Enable linc-qc for abcd and hbcd modes by default

xcp_d/cli/parser.py, xcp_d/tests/test_cli_run.py
Closes none, but addresses an issue reported by @juliegrier. Basically, it's currently unclear how XCP-D works if users use `-p none` (no denoising) and `--custom-confounds` (external regressors to be used for denoising). Logically, it makes more sense to automatically change `-p` to `custom` in that scenario than to ignore `--custom-confounds`.
- If nuisance regressors are set to `none`, but custom confounds are provided, then issue a warning and change the nuisance regressor option to `custom`.
=> Explicitly check for `-p none` and `--custom-confounds`

.github/ISSUE_TEMPLATE/bug_report.md, docs/installation.rst, docs/links.rst, docs/usage.rst, xcp_d/cli/run.py, xcp_d/config.py
Closes #1230.
- Finish replacing "Singularity" with "Apptainer" in documentation.
- Drop mention of Singularity version requirements because I don't think we have those same requirements for Apptainer.
=> Document the apptainer version requirements

xcp_d/data/io_spec.yaml, xcp_d/utils/bids.py
Closes none, but addresses a bug reported by @erikglee.
Here's the issue: With T1w+T2w derivatives in Nibabies, the `anat_dseg` file may have `space-T2w` instead of no space entity like we expect. 
Fixing this led us down the rabbit hole, as the T1w and T2w produced by Nibabies are in different spaces (native T1w and native T2w, respectively). XCP-D assumes that they would be in the same space, so the same anatomical-to-template transform could be applied to both. Unfortunately, that's not the case with Nibabies derivatives. Also, there is no T1w-to-T2w transform that we could use to get them in the same space (not that I'd want to do that, since it would be an extra transform to apply).
The only things this should affect are the executive summary brainsprite and figures where templates …
=> Make collect_data work for T1w+T2w nibabies derivatives

xcp_d/utils/restingstate.py
Fixes a bug reported by @erikglee. Basically, `time_arr = np.arange(0, n_volumes * TR, TR)` and `time_arr = np.arange(n_volumes) * TR` _should_ produce the same array, but in some cases `n_volumes * TR` evaluates to `X.00000005` (or something similar), which trickes `np.arange` into putting another value in the array, making it longer than desired. I've switched to the latter approach, which shouldn't be susceptible to the same problem.
=> Account for floating point issues in ALFF time array creation

docs/workflows.rst, xcp_d/cli/parser.py, xcp_d/tests/test_cli.py, xcp_d/tests/test_cli_run.py
Closes #1227.
- Create a "none" `--mode` option, in which all of the parameters that are automatically set by other modes must be defined manually.
- Add `--output-type` parameter to control whether denoised data and time series are written as censored or interpolated. This was previously automatically determined based on the mode, but with "none" mode users need to define it explicitly.
=> Implement "none" mode

xcp_d/utils/bids.py
Closes #1239.
- If there's both a T1w and a T2w, but there's no T2w-to-template transform, use the T1w as the primary modality.
=> Fix collection in case of derivatives with T1w and T2w but T1w is primary

xcp_d/interfaces/nilearn.py, xcp_d/tests/test_utils_utils.py, xcp_d/utils/utils.py
Closes #1243. This doesn't affect the command-line interface or ingression of confounds. It simply prepares for a time when we'll be able to ingress voxel-wise confounds.
- Allow a list of voxel-wise confounds in `denoise_with_nilearn`.
=> Internally support voxel-wise confounds

xcp_d/utils/bids.py
Closes none, but addresses a bug discovered by Julia Moser.
Apparently XCP-D was including "space": None in the query, which is not right for finding the sphere files.
- Fix subject sphere query
=> Fix subject sphere query

.circleci/config.yml, pyproject.toml, xcp_d/interfaces/workbench.py, xcp_d/tests/test_cli.py, xcp_d/tests/test_smoothing.py, xcp_d/tests/test_workflows_anatomical.py, xcp_d/tests/utils.py, xcp_d/workflows/anatomical/parcellation.py, xcp_d/workflows/anatomical/plotting.py, xcp_d/workflows/anatomical/surface.py, xcp_d/workflows/anatomical/volume.py, xcp_d/workflows/bold/cifti.py, xcp_d/workflows/bold/connectivity.py, xcp_d/workflows/bold/metrics.py, xcp_d/workflows/bold/nifti.py, xcp_d/workflows/bold/plotting.py, xcp_d/workflows/bold/postprocessing.py, xcp_d/workflows/parcellation.py
Closes none, but addresses an issue identified by @mattcieslak.
- For any single-threaded nodes in any workflow, drop `n_procs=omp_nthreads`.
- Also drop `omp_nthreads=*` from any nodes using that. Pretty sure it doesn't do anything. 
- Create a WBCommand base interface that sets OMP_NUM_THREADS.
- Use the MultiProc plugin for integration tests, which speeds things up by a fair amount.
=> Remove n_procs for nodes that do not use multiple cores

xcp_d/interfaces/restingstate.py
The `n_threads` input shouldn't trigger a re-run if it changes. This prevents that from happening
=> Don't rerun alff if num threads changes

xcp_d/cli/parser.py, xcp_d/cli/run.py, xcp_d/cli/workflow.py, xcp_d/config.py, xcp_d/data/tests/config.toml, xcp_d/tests/test_cli.py, xcp_d/tests/test_workflows_anatomical.py, xcp_d/tests/test_workflows_connectivity.py, xcp_d/tests/test_workflows_metrics.py, xcp_d/tests/test_workflows_plotting.py, xcp_d/tests/tests.py, xcp_d/workflows/anatomical/outputs.py, xcp_d/workflows/anatomical/parcellation.py, xcp_d/workflows/anatomical/plotting.py, xcp_d/workflows/anatomical/surface.py, xcp_d/workflows/anatomical/volume.py, xcp_d/workflows/base.py, xcp_d/workflows/bold/concatenation.py, xcp_d/workflows/bold/connectivity.py, xcp_d/workflows/bold/metrics.py, xcp_d/workflows/bold/outputs.py, xcp_d/workflows/bold/plotting.py, xcp_d/workflows/bold/postprocessing.py, xcp_d/workflows/parcellation.py, xcp_d/workflows/plotting.py
Closes none.
- Drop config.execution.xcp_d_dir in favor of the existing config.execution.output_dir.
- Rename any figure-generating datasinks to start with `ds_report_` and drop `datatype="figures"`.
- Loop over nodes and automatically set `datatype` to `"figures"` for nodes starting with `ds_report_`.
- Loop over nodes and automatically set `base_directory` to `config.execution.output_dir` for nodes starting with `ds_`.
=> Remove xcp_d_dir and clean datasinks

.circleci/config.yml
Apparently 19.03.13 is no longer available.
=> Bump Docker deployment version

xcp_d/config.py, xcp_d/tests/data/ds001419_cifti_filter.json, xcp_d/tests/test_cli.py
Closes none. Should make it so `--task-id` is correctly used to filter BOLD scans.
- Path `task_id` into `bids_filters`.
=> Patch task_id into bids_filters

xcp_d/cli/parser.py, xcp_d/tests/conftest.py, xcp_d/tests/test_cli.py, xcp_d/workflows/anatomical/surface.py
Closes none. Unfortunately some tests fail because of a cache issue from #1255.
- Make `--fs-license-file` (which is unused) optional.
- Drop `mrisconvert` command in surface normalization workflow. This was an artifact from when we collected the `sphere.reg` file from Freesurfer. Now that fMRIPrep and Nibabies write out the sphere files as a GIFTI, we no longer need to convert it to GIFTI.
- Remove FREESURFER_LICENSE from environment variables.
=> Remove Freesurfer node from surface normalization workflow

docs/installation.rst, docs/usage.rst, docs/workflows.rst, xcp_d/cli/combineqc.py, xcp_d/cli/parser.py, xcp_d/cli/workflow.py, xcp_d/config.py, xcp_d/interfaces/execsummary.py, xcp_d/tests/test_cli.py, xcp_d/utils/bids.py, xcp_d/workflows/base.py, xcp_d/workflows/bold/plotting.py
Closes none. Splits out a backward-incompatible change from #1265.
- Rename the `--derivatives` parameter to `--datasets`, to prepare to allow BIDS-Atlas datasets.
- Change `xcp-d` to `XCP-D` throughout the package.
=> Rename `--derivatives` parameter to `--datasets`

xcp_d/utils/atlas.py
Closes #1303.
- Don't raise an error in `select_atlases` if external atlases are provided.
=> Fix bug with surfaces and external atlases

xcp_d/cli/parser.py, xcp_d/interfaces/censoring.py, xcp_d/interfaces/connectivity.py, xcp_d/tests/test_cli.py, xcp_d/tests/test_utils_confounds.py, xcp_d/utils/boilerplate.py, xcp_d/utils/confounds.py, xcp_d/utils/doc.py
Closes #1272 and closes #1278. Thanks to @cindyhfls for detecting the problem and figuring out the solution.
- Divide the `--motion-filter-order` parameter by 4 instead of 2 when using the "notch" motion filter, as `iirnotch` is a second-order filter and `filtfilt` applies the filter both forwards and backwards (equaling 4 total applications).
- Update the documentation to reflect this.
- Fix a surprising bug related to exact-time correlation matrices. Not sure why it never came up before. See [8f8816f](https://github.com/PennLINC/xcp_d/pull/1300/commits/8f8816f0d3fd0a6ba37777328df5bf9dee70ec11).
=> Apply notch filter appropriate number of times based on `--motion-filter-order`

xcp_d/tests/test_utils_bids.py, xcp_d/utils/bids.py
Closes #1305.
- Include `'space': 'fsLR', 'den': '32k'` in mesh query when standard-space mesh files are found.
- Update test to ensure it would fail in the old scenario, but passes with the fix.
=> Fix ingression of standard-space mesh files

xcp_d/cli/parser.py
Related to https://github.com/PennLINC/xcp_d/issues/1306#issuecomment-2474199309.
Replace xcp_d.readthedocs.io with xcp-d.readthedocs.io.
=> Fix links to documentation

docs/workflows.rst, xcp_d/cli/parser.py
Closes none. Follows up on #1320.
- Document nichart mode.
=> Document the nichart mode

xcp_d/workflows/bold/postprocessing.py
When `--dummy-scans` is set to `auto` (the default), XCP-D attempts to infer the right number of dummy volumes from the fMRIPrep confounds file. However, starting in #1255, I connected the output of a node that _removes_ the dummy volume columns from the confounds file to the node that looks for those columns, which resulted in dummy volumes not being flagged and removed by the post-processing workflow. This was identified by a user, Bianca Serio, in https://neurostars.org/t/filenotfounderror-no-bold-data-found-in-allowed-spaces-fslr/30968.
**THIS BUG AFFECTS VERSIONS 0.10.0rc1 - 0.10.0**
- Use unfiltered confounds file to identify non-steady-state (i.e., dummy) volumes to remove from the BOLD data, rather than the filtered version that only include motion columns.
=> Use confounds file with non-steady-state columns to identify dummy volumes

docs/outputs.rst, xcp_d/cli/parser.py, xcp_d/workflows/anatomical/surface.py
Closes #1322.
- Document how the warped surfaces are kind of in MNI152NLin6Asym space.
=> Clarify that warped surfaces can be overlaid on the MNI152NLin6Asym template

.circleci/config.yml, Dockerfile, xcp_d/tests/run_local_tests.py
Closes none, but fixes the weird brainsprites we've been seeing for non-normalized surfaces.
- Switch back from 2.0.0 to 1.5.0 for connectome workbench.
=> Downgrade connectome workbench version

xcp_d/data/executive_summary_templates/executive_summary.html.jinja
Currently the boilerplate, markdown and latex in the executive summary are being rendered as plain text. This should revert them to be rendered as html.
=> Stop autoescaping the boilerplate

xcp_d/workflows/base.py
Closes none. This is just a minor optimization that eliminates a step that warps the standard-space anatomical brain mask to anatomical space when it's not necessary.
- Don't estimate the head radius if `--head-radius` isn't "auto".
=> Only estimate head radius if necessary

xcp_d/tests/test_cli.py, xcp_d/workflows/anatomical/parcellation.py
Closes none, but addresses bug detected by user in https://neurostars.org/t/issue-with-running-xcp-d-with-nifti-file-format/31702.
- Hardcode the atlas format in `init_parcellate_surfaces_wf` as "cifti", so that it uses CIFTI atlases to parcellate surfaces.
- I also tested it out in ds001419_nifti test and it worked. I reverted that change since creating the brainsprite takes a while.
=> Support `--abcc-qc` with `--file-format nifti`

docs/usage.rst
Relates to #1378 
Apply consistent formatting and command usage across examples in `usage.rst`
`usage.rst`
=> Apply consistency across XCP-D quick-start instructions

xcp_d/ingression/utils.py, xcp_d/interfaces/connectivity.py, xcp_d/interfaces/utils.py, xcp_d/tests/test_despike.py, xcp_d/tests/test_interfaces_utils.py, xcp_d/tests/test_utils_confounds.py, xcp_d/utils/confounds.py, xcp_d/utils/plotting.py, xcp_d/utils/restingstate.py
Closes #1395.
- Replace uses of numpy.mean and numpy.std with numpy.nanmean and numpynanstd, respectively.
- For corrcoefs, replace NaNs with zeros.
=> Make calculations robust to NaNs

xcp_d/workflows/bold/plotting.py
Closes none.
- Coregistration QC was using the BOLD mask warped to anatomical space in place of the anatomical mask, which was a bug. Coregistration QC measures were all 1 before because it was comparing the BOLD brain mask against itself.
=> Warp anat mask to anat space for coreg QC

xcp_d/interfaces/connectivity.py
Closes #1418.
- If a background label (index = 0) is present in an atlas's TSV file, remove it in ConnectPlot.
=> Remove background label in ConnectPlot

xcp_d/data/tests/skeletons/nibabies_crosssectional.yml, xcp_d/data/tests/skeletons/nibabies_longitudinal_one_to_all.yml, xcp_d/data/tests/skeletons/nibabies_longitudinal_one_to_one.yml, xcp_d/tests/test_utils_bids_collect_data.py, xcp_d/utils/bids.py, xcp_d/workflows/base.py
Closes none, but fixes bus introduced in #1438.
- Remove manual session patching in bids_filters from base.py.
- Update collect_data (in xcp_d/utils/bids.py) to accept and propagate anat_session and func_sessions.
- Enhance tests to validate these changes across cross‐sectional and longitudinal datasets.
=> Fix session-wise collection

xcp_d/tests/test_utils_bids.py, xcp_d/utils/bids.py, xcp_d/workflows/base.py
Closes none, but fixes bug introduced in #1438.
- Update collect_mesh_data and collect_morphometry_data (in xcp_d/utils/bids.py) to accept and propagate anat_session.
- Enhance tests to validate these changes across cross‐sectional and longitudinal datasets.
=> Fix session-wise collection of surface files

xcp_d/workflows/base.py
Closes none, but continues from #1438.
- Include anatomical and functional sessions in `init_single_subject_wf` workflow name.
=> Make workflow name unique for session-wise processing

xcp_d/interfaces/censoring.py, xcp_d/tests/test_interfaces_censoring.py, xcp_d/workflows/bold/postprocessing.py
Closes #1445.
- Add parameter to `RemoveDummyVolumes` interface called `dummy_scan_source`. Pass the fMRIPrep confounds file in as `dummy_scan_source` and the filtered motion parameters as `motion_file`.
=> Write out filtered motion parameters when dummy-scans is not zero

xcp_d/ingression/abcdbids.py, xcp_d/ingression/hcpya.py, xcp_d/ingression/utils.py
Closes none, but addresses a bug identified by @rosemccollum. Basically, in 0.10.7 we started using a brain mask NIfTI in the CIFTI workflow in order to mask out non-brain voxels in the executive summary (see #1425), but I didn't add a brain mask to the converted ABCD/HCP data.
=> Ingress BOLD brain mask in ABCD-BIDS and HCP processing

CITATION.cff, xcp_d/data/nuisance/acompcor.yml, xcp_d/data/nuisance/acompcor_gsr.yml, xcp_d/tests/test_interfaces_censoring.py
Closes #1497.
Also remove mean WM and mean CSF from acompcor_gsr.
This pull request addresses issue #1497. It includes changes in two config yaml files for aCompCor confound regression:
**1. xcp_d/data/nuisance/acompcor.yml**
The WM and CSF components now includes the first 5 [0-4] components instead of components 2-6 [1-5] as before.
^w_comp_cor_0[0-4]$
^c_comp_cor_0[0-4]$
**2. xcp_d/data/nuisance/acompcor_gsr.yml** 
The same change as in acompcor.yml, in addition to removal of the mean CSF and mean WM signals. 
These two confound signals were removed to maych the confound documentation table (https://xcp-d.readthedocs.io/en/latest/workflows.html#id20).
The removal of these two confound signals will probably not make a big difference, as mean CSF and mean WM signals together lead to …
=> Fix WM and CSF component selection in acompcor and acompcor_gsr

xcp_d/cli/parser.py
Closes none, but addresses a documentation issue identified by @singlesp.
=> Change metavar for `--mem-mb` parameter
